src/shared/ui/survey/RadioActivityItem/RadioActivityItem.tsx, src/widgets/activity-group/model/hooks/useActivityGroups.ts
For some reason Tamagui's component cannot accept undefined/null to as a value that resets the radio group.\n In that case, we have to pass an empty string to make sure no radio button is displayed as selected
https://mindlogger.atlassian.net/browse/M2-1451
=> fix(radio): Fixed empty value ignore

src/entities/notification/model/mappers/mapToTriggerNotifications.ts
The android styling cause the following error: Error: notifee.createTriggerNotification(*) 'notification.android.style' BigTextStyle: 'text' expected a valid string value.]  It may have something to do with Notifee as we had a guard that checked if notificationBody is undefined or null then pass empty string to the 'text' property.
https://mindlogger.atlassian.net/browse/M2-1757
=> fix(notification): Removed unused styles for android texts

src/features/streaming/ui/ConnectionModal.tsx
Improved Live connection form UI, added KeyboardAvoidingView, as on small ios devices, keyboard was covering the submit button
Before:
After:
=> Improved Live connection form UI

src/screens/config/theme.tsx, src/screens/ui/AppletBottomTabNavigator.tsx
[M2-4225](https://mindlogger.atlassian.net/browse/M2-4225)
AppletBottomTabBar paddingBottom issues on Ipad 7th (because safeAreaBottom = 0)
[M2-4225]: https://mindlogger.atlassian.net/browse/M2-4225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Before
After
=> Fixed M2-4225 AppletBottomTabBar paddingBottom issues on Ipad 7th

src/shared/lib/hooks/useAudioPlayer.ts
[M2-4428](https://mindlogger.atlassian.net/browse/M2-4428) not showing loader on android, when audio track is resumed playing
[M2-4428]: https://mindlogger.atlassian.net/browse/M2-4428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-4428 not showing loader on android, when audio track is resumed playing

src/entities/drawer/ui/DrawingBoard.tsx, src/shared/ui/SketchCanvas/DrawingGesture.ts, src/shared/ui/SketchCanvas/SketchCanvas.tsx
https://mindlogger.atlassian.net/browse/M2-4920
=> fix(drawing): Moved creation of point timestamps from JS to UI thread

package.json, src/entities/activity/lib/types/activity.ts, src/entities/activity/model/mappers.ts, src/features/pass-survey/lib/types/payload.ts, src/features/pass-survey/model/tests/ScoresCalculator.collectMaxScores.test.ts, src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForCheckboxes.test.ts, src/shared/api/services/ActivityItemDto.ts, src/shared/ui/survey/CheckBox/CheckBoxActivity.item.tsx, src/shared/ui/survey/CheckBox/types.ts
🔗 [Jira Ticket M2-5047](https://mindlogger.atlassian.net/browse/M2-5047)
- Adds the "None" option support
- Slightly refactors `onItemValueChanged` by separating concerns of adding and removing of options.
=> M2-5047: Add None option support

src/features/pass-survey/model/AnswerValidator.ts, src/features/pass-survey/model/hooks/useActivityStepper.ts
🔗 [Jira Ticket M2-5044](https://mindlogger.atlassian.net/browse/M2-5044)
🔗 [Jira Ticket M2-4793](https://mindlogger.atlassian.net/browse/M2-4793)
This PR fixes the logic within `AnswerValidator.isOutsideOfValues` which was using `ConditionalLogicModel.isBetweenValues` instead of `ConditionalLogicModel.isOutsideOfValues`.
I also took the opportunity to update the logic for the `Next` button because I noticed while testing that the respondent may discover the logic for how to unlock some steps that they may other not have, just by playing with the slider. This brings the mobile app in line with web (see https://github.com/ChildMindInstitute/mindlogger-web-refactor/pull/358).
The logic is incorrect. It advances to the next question on the value 3, when it should only advance when the value …
=> [M2-5044] [M2-4793] 'outside of' rule for slider works incorrectly

src/features/applets-refresh/model/hooks/useRefresh.ts, src/features/enter-foreground/model/hooks/index.ts, src/features/enter-foreground/model/hooks/useAnalyticsEventTrack.ts, src/features/send-application-logs/ui/SendApplicationLogsForm.tsx, src/screens/ui/RootNavigator.tsx, src/shared/lib/analytics/AnalyticsService.ts
🔗 [Jira Ticket M2-4992](https://mindlogger.atlassian.net/browse/M2-4992)
🔗 [Jira Ticket M2-4999](https://mindlogger.atlassian.net/browse/M2-4999)
This PR adds some new mixpanel events
-  adds mixpanel events for the case when the app switched from background to foreground state
- adds mixpanel events for the cases when user sends logs from the upload-logs screen
=> M2-4992, M2-4999: Mixpanel Tracking: Mobile App Re-Open ; Upload logs screen

src/features/pass-survey/model/AlertsExtractor.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromCheckbox.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromRadio.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromSlider.test.ts, src/features/pass-survey/model/tests/ScoresCalculator.collectMaxScores.test.ts, src/features/pass-survey/model/tests/testHelpers.ts
🔗 [Jira Ticket M2-5363](https://mindlogger.atlassian.net/browse/M2-5363)
🔗 [Jira Ticket M2-5364](https://mindlogger.atlassian.net/browse/M2-5364)
🔗 [Jira Ticket M2-5365](https://mindlogger.atlassian.net/browse/M2-5365)
This PR adds unit tests that cover AlertsExtractor logic for not stacked item types
- add three unit test modules
- add testHelpers module that contains create/populate functions
=> M2-5363,M2-5364,M2-5365: [Mobile] Unit tests for AlertsExtractor for not stacked items

android/app/src/main/java/lab/childmindinstitute/data/MainApplication.java, android/app/src/main/java/lab/childmindinstitute/data/image_conversion/ImageConversionModule.java, android/app/src/main/java/lab/childmindinstitute/data/image_conversion/ImageConversionPackage.java, src/shared/lib/constants/index.ts, src/shared/lib/utils/imageConverter.ts, src/shared/lib/utils/index.ts, src/shared/ui/survey/MediaItems/PhotoItem.tsx
🔗 [Jira Ticket M2-5489](https://mindlogger.atlassian.net/browse/M2-5489)
- the way the app handles images added from library on some Android 13 devices
This PR adds:
- a native Android module that is capable of converting HEIC images into JPG ones.
[react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker) does this conversion under the hood but it works on iOS devices only. Modern Android devices on Android 13, such as Samsung A52 can take photos and store them in HEIC format. react-native-image-picker does not cover this case (yet) and has not been updated since Dec 4, 2023 at the time of writing.
Writing a converter on the backend / DevOps side is possible but it seems too asynchronous (the conversion would have taken place on …
=> M2-5489 Add HEIC to JPG converter for Android

patches/react-native-gesture-handler+2.14.1.patch, src/shared/ui/SketchCanvas/DrawingGesture.ts
🔗 [Jira Ticket M2-5292](https://mindlogger.atlassian.net/browse/M2-5292)
The issue happens from time to time on iOS devices. It is sometimes hard to reproduce but basically, the problem is that sometimes drawing events may have the same timestamp.
- the way how timestamps are created for each "move" event of Pan Responder.
- the iOS native module of React Native Gesture Handler (patch).
Steps to reproduce:
- Add the following code to the onTouchProgress function which is located in DrawingBoard.tsx:
- Open an activity with the Drawing Item
-  Draw a spiral (or anything else) for 5 minutes (try to not interrupt the line, don’t raise a finger/stylus)
OR draw 90 lines with different speed
**Expected outcome:** Alert window doesn't pop up.
After numerous trials and tests, it …
=> M2-5292 Duplicated timestamps in the drawing-response

.github/pull_request_template.md
🔗 [Jira Ticket M2-5512](https://mindlogger.atlassian.net/browse/M2-5512)
This PR defines a [GitHub pull request description template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) to act as a guide for developers to use when opening pull requests on the `mindlogger-app-refactor` repository.  GitHub will start using this as this repository's pull request template once this is merged to the default branch (`dev`).
- a new [GitHub pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
=> M2-5512: add PR template for GitHub pull requests

src/entities/notification/model/factory/NotificationBuilder.ts, src/entities/notification/model/factory/NotificationDaysExtractor.ts, src/entities/notification/model/factory/tests/NotificationBuilder.alwaysAvailable.test.ts, src/entities/notification/model/factory/tests/NotificationBuilder.daily.test.ts, src/entities/notification/model/factory/tests/NotificationDaysExtractor.test.ts, src/entities/notification/model/factory/tests/testHelpers.ts, src/features/pass-survey/model/AlertsExtractor.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromStackedCheckbox.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromStackedRadio.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromStackedSlider.test.ts, src/features/pass-survey/model/tests/testHelpers.ts
🔗 [Jira Ticket M2-5366](https://mindlogger.atlassian.net/browse/M2-5366)
🔗 [Jira Ticket M2-5367](https://mindlogger.atlassian.net/browse/M2-5367)
🔗 [Jira Ticket M2-5368](https://mindlogger.atlassian.net/browse/M2-5368)
This PR adds unit tests that cover AlertsExtractor logic for stacked item types
- Added unit tests for AlertsExtractor module: extractFromStackedSlider function
- Added unit tests for AlertsExtractor module: extractFromStackedCheckbox function
- Added unit tests for AlertsExtractor module: extractFromStackedRadio function
- Slightly improved code for the extractFromStackedCheckbox
- Added fixes for notification-related unit-tests (missed mock)
=> M2-5366, M2-5367, M2-5368: unit tests for stacked items

src/shared/ui/SketchCanvas/DrawingGesture.ts
🔗 [Jira Ticket M2-5243](https://mindlogger.atlassian.net/browse/M2-5243)
- Method that calls the function that indicates the end of the gesture.
The previously used `onFinalize` function is called when the second (and further) touch is lifted even though maxPointers(1) is defined. That is because the React Native Gesture Handler internally dismisses the touch by calling the `fail()` function in the result of which `onFinalize` is called.
=> M2-5243: Duplicated lines produced by the Drawing Items

src/features/pass-survey/model/tests/AlertsExtractor.extractFromItem.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromSlider.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromStackedCheckbox.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.extractFromStackedRadio.test.ts, src/features/pass-survey/model/tests/AlertsExtractor.test.ts, src/features/pass-survey/model/tests/testHelpers.ts
🔗 [Jira Ticket M2-5369](https://mindlogger.atlassian.net/browse/M2-5369)
🔗 [Jira Ticket M2-5370](https://mindlogger.atlassian.net/browse/M2-5370)
- Unit tests for AlertsExtractor -> extractFromItem function
- Unit tests for AlertsExtractor, penetration
- Unit tests minor improvements
=> M2-5369, M2-5370 unit tests for alerts-extractor: extract-from-item and penetration tests

ios/Podfile.lock, jest.setup.js, package.json, src/jobs/request-interception.ts, src/shared/lib/constants/dateTime.ts, yarn.lock
🔗 [Jira Ticket M2-5899](https://mindlogger.atlassian.net/browse/M2-5899)
- [react-native-localize](https://github.com/zoontek/react-native-localize)
- X-Timezone header in the request interceptor.
=> M2-5899: Added X-Timezone header

src/entities/applet/model/slice.ts, src/entities/streaming/model/slice.ts, src/features/login/ui/LoginForm.tsx, src/shared/lib/index.ts, src/shared/lib/redux-state/actions.ts, src/shared/lib/redux-state/index.ts
🔗 [Jira Ticket M2-5912](https://mindlogger.atlassian.net/browse/M2-5912)
- Common redux action that is used to clean up certain parts of state
- Usage of the action in the `applets` reducer
- Usage of the action in the `streaming` reducer
No need to clean up the whole global state on logout/login. The best practice is to use a common action that can be used through the '.extraReducer' function on slices: https://redux-toolkit.js.org/api/createSlice#extrareducers
=> M2-5912: Added action to clean up certain parts of state

package.json, src/entities/activity/lib/services/AnswersUploadService.ts, src/entities/activity/lib/types/uploadAnswers.ts, src/shared/api/services/answerService.ts, src/shared/lib/utils/dateTime.ts, src/widgets/survey/ui/Finish.tsx, src/widgets/survey/ui/Intermediate.tsx
🔗 [Jira Ticket M2-6036](https://mindlogger.atlassian.net/browse/M2-6036)
- Timezone offset calculation
- Assigning the offset to the responses at the moment of finishing an activity
The previous implementation considered having a timezone in the request header (X-Timezone) that the Backend server picked up and stored in the DB along with the received responses.
However, in the case when the actual **moment of finishing an activity** and the actual **moment of sending the data** over to the server are different and the user changes their timezone then it may lead to unexpected data in the DB.
That is why it was decided to save a timezone offset at the moment when the user finishes the activity to keep the data consistent.
=> M2-6036: Timezone offset in answers

ios/MindloggerMobile.xcodeproj/project.pbxproj, ios/Podfile.lock
React Native 0.73.x works correctly Cocoapods of < 0.15 version because of a bug. React Native team recommends using versions >= 1.13 and < 1.15:
=> Set correct cocoapods version that works with RN 0.73

ios/MindloggerMobile.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/PrivacyInfo.xcprivacy
🔗 [Jira Ticket M2-5938](https://mindlogger.atlassian.net/browse/M2-5938)
Changes include a PrivacyInfo file to resolve issues raised by App Store Connect:
> ITMS-91053: Missing API declaration - Your app’s code in the “MindloggerMobile” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: …
=> M2-5938: Added PrivacyInfo file for iOS

ios/MindloggerMobile.xcodeproj/project.pbxproj, ios/MindloggerMobileUATDebug.entitlements, ios/MindloggerMobileUATRelease.entitlements
🔗 [Jira Ticket M2-6298](https://mindlogger.atlassian.net/browse/M2-6298)
This PR adds the missing UAT entitlements files so that the correct associated domain may be used in the UAT build. The app was previously using the staging entitlements files for the UAT build
=> M2-6298: Add UAT entitlements files

src/features/pass-survey/ui/ActivityStepper.tsx, src/shared/ui/Stepper/index.tsx
🔗 [Jira Ticket M2-6377](https://mindlogger.atlassian.net/browse/M2-6377)
- A/B Trails - Not adding "DONE" event to userActions when user clicks skip on the last round of AbTrails
Added payload to onEndReached function , which includes shouldIgnoreUserActionTrack: boolean value.
=> M2-6377: A/B Trails: There is extra 'press_done' event when round was skipped

jest.config.ts, jest.setup.js, src/entities/drawer/lib/utils/constants.ts, src/entities/drawer/lib/utils/helpers.ts, src/entities/drawer/lib/utils/index.ts, src/entities/drawer/test/helpers.test.ts, src/entities/drawer/ui/DrawingBoard.tsx, src/entities/drawer/ui/DrawingTest.tsx, src/features/pass-survey/ui/ActivityItem.tsx, src/shared/ui/SketchCanvas/SketchCanvas.tsx, src/shared/ui/SketchCanvas/useDrawingGesture.ts
🔗 [Jira Ticket M2-6037](https://mindlogger.atlassian.net/browse/M2-6037)
- Changed the`DrawingTest` component with a brand new layout that supports the ratio between the Drawing Canvas and the Example Image
- Unit tests
- Default 0.38 / 0.62 ratio
| (New Approach)                                |
| ------------------------------------- |
| ![image](https://github.com/ChildMindInstitute/mindlogger-app-refactor/assets/20073193/effa407e-f951-4c5f-983a-8084a4446c30) |
=> M2-6037: Allow to divide the space 50/50 between Drawing Example and Drawing Area

src/entities/drawer/lib/utils/helpers.ts, src/entities/drawer/test/helpers.test.ts, src/entities/drawer/ui/DrawingTest.tsx, src/features/pass-survey/ui/ActivityItem.tsx, src/shared/lib/hooks/index.ts, src/shared/lib/hooks/useImageDimensions.ts
https://mindlogger.atlassian.net/browse/M2-6440 https://mindlogger.atlassian.net/browse/M2-6442
🔗 [Jira Ticket M2-6440](https://mindlogger.atlassian.net/browse/M2-6440)
🔗 [Jira Ticket M2-6442](https://mindlogger.atlassian.net/browse/M2-6442)
🔗 [Jira Ticket M2-6442](https://mindlogger.atlassian.net/browse/M2-6437)
Changed the algorithm responsible for calculating elements so that it:
- works out the example image height: the example image should have a real height within but not exceeding 38% of the drawing component’s height
- sets the height of the drawing item that should not exceed the sum of the example image height and the canvas board.
=> M2-6440, M2-6442, M2-6437: Fixed layout for very narrow example images

src/entities/applet/model/slice.ts, src/screens/model/checkEntityAvailability.ts, src/widgets/activity-group/model/factories/GroupUtility.ts, src/widgets/survey/model/hooks/useAutoCompletion.ts, src/widgets/survey/model/services/ConstructCompletionsService.ts, src/widgets/survey/model/services/tests/ConstructCompletionsService.test.ts, src/widgets/survey/model/services/tests/testHelpers.ts, src/widgets/survey/ui/Finish.tsx, src/widgets/survey/ui/Intermediate.tsx
🔗 [Jira Ticket M2-6301](https://mindlogger.atlassian.net/browse/M2-6301)
- Fixes how the mobile and server side save/keep/analyze the date-time moment of activity/flow completion. In case of autocompletion this moment should be equal to availableTo - the right part of the current time window based on the event. Previously, for autocompletion it was Date.now() and that value set to the dto that transfered to server, whereas mobile app considered availableTo instead.
- Fixes how the available/scheduled group evaluators filter activitiy+event items based on dateFrom, dateTo. Previously we had a bug - endDate handled wrong way - considered start of day (00:00:00) i.o. end of day (23:59:59)
- Fixes the progress sync service - as consequence of the 1st error in this list - the …
=> M2-6301: NIMH Applet Scheduling is not working as expected

android/app/src/main/AndroidManifest.xml
🔗 [Jira Ticket M2-6587](https://mindlogger.atlassian.net/browse/M2-6587)
- Changes in permissions in the AndroidManifest file according to https://developer.android.com/about/versions/14/changes/schedule-exact-alarms
=> M2-6587: Swap USE_EXACT_ALARM for SCHEDULE_EXACT_ALARM

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, ios/MindloggerMobile.xcodeproj/project.pbxproj, package.json, yarn.lock
🔗 [Jira Ticket M2-6587](https://mindlogger.atlassian.net/browse/M2-6587)
- Updating version of react-native-background-fetch
- Setting `maxSdkVersion` for `SCHEDULE_EXACT_ALARM` permission explicitly.
`react-native-background-fetch` overwrites `maxSdkVersion` to `33` and then Android's manifest merger applies this value to the final manifest file. That led to the situation when `SCHEDULE_EXACT_ALARM` was not on Android 14 (SDK 34) and not working local trigger notifications. It was decided to hardcode the `maxSdkVersion` value on `AndroidManifest.xml` and not let anything overwrite it
=> M2-6587: alarm permission issue

android/app/src/main/AndroidManifest.xml
🔗 [Jira Ticket M2-6600](https://mindlogger.atlassian.net/browse/M2-6600)
I've included an explicit `android:pathPrefix` attribute in the deep linking intent filter in the Android manifest file. Right now we only support one path for deep linking: `/password-recovery/...`. By explicitly proving this value at build time, it will prevent the OS from launching the app for any other paths on an associated domain.
Clicking an invite link in an email will launch the production app
https://github.com/ChildMindInstitute/mindlogger-app-refactor/assets/14842108/d55ae339-4533-41ca-b1f1-7fd5661cd89e
Clicking an invite link in an email will launch the device's browser
https://github.com/ChildMindInstitute/mindlogger-app-refactor/assets/14842108/47574bf8-1abf-478d-b0d0-7d497474c959
Password reset links …
=> hotfix: Fix infinite deep linking redirection on Android (M2-6600)

src/app/model/migrations/MigrationFactory.ts, src/app/model/migrations/MigrationRunner.ts
Migration keys need to be started from "1".
Also, the `map` function call was fixed in the `getMigrationKeys` method so that it accepts an anonymous arrow function. The problem was that the map's callback provides three arguments: item, index and array; at the same time `parseInt` can accept two arguments: string to parse and radix. Since the the map function was called this way `.map(parseInt)` that made parseInt accept two arguments and change the radix breaking the logic.
=> fix(migration): Changed migration keys to corresponds their versions

src/entities/drawer/ui/DrawingTest/DrawingTestNewLayout.tsx
Fixed passing a wrong value to the `getElementsDimensions` function due to a mistake in a merge conflict resolvement
=> fix(drawing): Fixed reducing of drawing height after a merge conflict

android/app/src/main/AndroidManifest.xml
🔗 [Jira Ticket M2-6894](https://mindlogger.atlassian.net/browse/M2-6894)
Disabled unnecessary USE_FULL_SCREEN_INTENT used by Notifee to satisfy Google Policy:
=> M2-6894: Disabled USE_FULL_SCREEN_INTENT to satisfy Google Policy

android/app/build.gradle, android/app/src/production/google-services.json
🔗 [Jira Ticket M2-6930](https://mindlogger.atlassian.net/browse/M2-6930)
Same PR as https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/800 but to `2.0.4-hotfix.1` release branch
1. Added `applicationIdSuffix` for Production Flavor to be able to upload new production builds to new app on Google Play Console.
2. Added a new `google-services.json `for Production Flavor to enable Crashlytics and Firebase Messaging
=> M2-6930: Added new application Id for Production app to 2.0.4-hotfix

src/entities/applet/model/hooks/useStartEntity.ts, src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts, src/screens/model/checkEntityAvailability.ts, src/screens/ui/RootNavigator.tsx, src/shared/lib/hooks/index.ts, src/shared/lib/hooks/useOnForegroundDebounced.ts, src/shared/lib/hooks/useOnceRef.ts, src/shared/lib/hooks/useOnlineEstablished.ts, src/widgets/activity-group/ui/ActivitySectionList.tsx, src/widgets/survey/model/hooks/index.ts, src/widgets/survey/model/hooks/useAutoCompletion.ts, src/widgets/survey/model/hooks/useAutoCompletionExecute.ts, src/widgets/survey/model/hooks/useOnAutoCompletion.ts, src/widgets/survey/ui/UploadRetryBanner.tsx
🔗 [Jira Ticket M2-7248](https://mindlogger.atlassian.net/browse/M2-7248)
🔗 [Jira Ticket M2-7246](https://mindlogger.atlassian.net/browse/M2-7246)
- Fix for iOS: swipe from up to down - previousy -  the event 'active' registered
- Fix for restart-resume, when alert opened for a long time, the entity could expire
- Lite refactoring in RootNavigator: triggers for autocompletion when: go-to-foreground, on-app-start, go-to-online
- Fix for isQueueEmpty when autocompletion with upload works, to make decision if blocker screens should be opened
=> M2-7248, M2-7246: bugfixes for autocompletion delivery part 2

src/shared/ui/survey/CheckBox/CheckBoxCard.tsx
🔗 [Jira Ticket M2-7230](https://mindlogger.atlassian.net/browse/M2-7230)
Changes include very minor changes like removing console.log and animation from @react-native-community/checkbox which made the component look slower on press.
=> M2-7230: Removed console.log & unnecessary animation layer

src/shared/lib/featureFlags/FeatureFlags.types.ts
It just fixes feature flags naming convention: from camelCase to dash-case. Apparently, LaunchDarkly for React Native accepts only the latter though they don't mention that in the docs.
=> fix(feature-flags): Change the flag name from camelCase to dash-case

src/shared/ui/survey/tests/DatePickerItem.test.tsx
After 
https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/833
I've got error (I'm under GMT+2/+3, ~12:30 PM)
🔗 [Jira Ticket M2-7464](https://mindlogger.atlassian.net/browse/M2-7464)
- Modified useless unit test to get practical sence
- Added another unit test to the same component
The test itself was wrong:
it("Should render new Date(0) when value is 1970-01-01", ... )
new Date(0) doesn't equal to new Date(1970,0,1) because the 1st is based on UTC time, the 2nd - on local.
So, I've changed it to:
it('Should consume new Date(1970, 0, 1) when props value is "1970-01-01"', ... )
Some information:
=> M2-7464: [Mobile] Fix DatePickerItem unit tests

src/features/pass-survey/model/pipelineBuilder.ts
🔗 [Jira Ticket M2-7538](https://mindlogger.atlassian.net/browse/M2-7538)
There is a dead simple filtering logic that filters out activity items that are not supported in the current version of the mobile app. This is the case when, for instance, the Admin Panel rolls out the release featuring new activity item types but the Mobile App is still in the testing/review phase: admins can start adding news items right away and the mobile app should just those items.
=> M2-7538 unknown item types

src/app/ui/AppProvider/ReduxProvider.tsx, src/shared/lib/redux-state/store.ts, src/widgets/survey/model/services/ConstructCompletionsService.ts
🔗 [Jira Ticket M2-7646](https://mindlogger.atlassian.net/browse/M2-7646)
- Redux Persistor is now an exportable variable
- Flush persistor as soon as an activity is completed.
If a user starts an activity, submits it, and immediately kills the app while "Processing Answers" is displayed, the activity might remain in an in-progress state when the app reopens.
This behavior is likely due to how Redux Persist is configured with the following settings:
```
export const persistConfig = {
key: 'root',
throttle: 1000,
storage: storage,
};
```
The `throttle` property is set to `1000`. This means that the application state is only written to disk in 1 second. This throttling is done for performance reasons, to batch updates, and to avoid overwhelming storage. [API …
=> fix(redux): Made redux-persist flush as soon as activity completed

src/entities/applet/model/slice.ts, src/widgets/survey/model/services/ConstructCompletionsService.ts
🔗 [Jira Ticket M2-7646](https://mindlogger.atlassian.net/browse/M2-7646)
- Slightly improved performance of `entityCompleted` reducer by reducing accessing and mutations of deeply nested properties. Redux Toolkit uses the `immer` library under the hood, which allows for direct state mutation but comes with some performance overhead.
- Moved the invocation of `entityCompleted` action up to the top of `constructForFinish` method. Previously, it was called after a set of mapper functions that contain some medium-heavy computations. That, in turn, caused a ~ 400ms delay in 1-item activity and up to ~700ms in 14-item activity. Now, after optimizations applied, it's ~150 ms in 14-item activity. Screenshot and performance measuring strategy described below.
Activity with 14 …
=> M2-7646: performance optimisation

src/entities/applet/model/services/RefreshService.ts, src/entities/applet/model/slice.ts
🔗 [Jira Ticket M2-7407](https://mindlogger.atlassian.net/browse/M2-7407)
This PR fixed an issue with missing normalization of `targetSubjectId` when the mobile app consumes entity completion records.
Currently, if an activity is auto-assign, or has a manual assignment to the respondent themselves, the mobile app internally treats that activity has having `targetSubjectId: null`.
However, for those activities, the `/answers/applet/completions` endpoint would return completion records that has the respondent's subject ID as the record's `targetSubjectId`.
Previously, these completion records were consumed without modification, and the presence of the respondent's `targetSubjectId` in completion records would cause a mismatch with the app's internal representation of `targetSubjectId: null`, …
=> fix: target subject ID normalization issue (M2-7407)

src/features/auth/model/cleanupData.ts, src/features/login/ui/LoginForm.tsx, src/features/logout/model/hooks.ts
🔗 [Jira Ticket M2-8113](https://mindlogger.atlassian.net/browse/M2-8113)
This PR removes the `await cleanupData()` from the "log out" hook.
The call was previously erroneously added by me. I thought it was an oversight that entity record/progression data were not cleared upon log out. I didn't realize retaining those data was an intended behaviour. So this PR removes the call to restore the previously intentional behaviour of not clearing entity record/progression data on log out.
N/A
1. Log into the mobile app
2. Start an activity but do not complete it
3. Exit the activity
4. Log out
5. Re-log into the mobile app
6. Resume the activity
... at this point, the activity should resume from where it was left off before existing and logging out.
N/A
=> fix: retaining local data on log out (M2-8113)

src/entities/activity/lib/hooks/useQueueProcessing.ts, src/widgets/survey/model/hooks/useAutoCompletion.ts
This PR adds an extra step to refresh applets data after answers are submitted.
This addition is meant to address the issue in [M2-8144](https://mindlogger.atlassian.net/browse/M2-8144), where when an daily activity is completed via notification, the activity does not disappear from the list of activities. In that case, the activity would disappear from the list if the user goes to refresh the applet. So this PR inserts the same refresh call to the end of the answers submission queue processor. So now, regardless if a activity is completed from the activities listing screen, or from notification, the applets will be refreshed after answers submission.
N/A
1. Create an applet
2. Create an activity
3. Set the activity …
=> fix: add applets refresh after answers submission (M2-8144)

src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
🔗 [Jira Ticket M2-8160](https://mindlogger.atlassian.net/browse/M2-8160)
This change should cause self-report, one-time-completion (or daily completion) activities/flows started by a notification tap result in the refreshed activities list to properly hide that activity/flow after it has been completed.
- User has an applet with activity that is set to **Auto-assign: true**
- Add new scheduled event for activity: 
- Repeats daily
- Notification = in the next 5 minutes (or however long it takes you to refresh and force-close the applet)
1. Refresh the applets list to ensure it has the latest updates from the activity (including the notification setting)
2. Kill (close) the app
3. Wait for the notification time
4. …
=> fix: Self-report assessments started by notification (M2-8144, M2-8160)

android/app/build.gradle, ios/MindloggerMobile.xcodeproj/project.pbxproj, src/entities/notification/model/factory/NotificationBuilder.ts
🔗 [Jira Ticket M2-8160](https://mindlogger.atlassian.net/browse/M2-8160)
When tapping a notification to start a manual self-report assessment, the `targetSubjectId` was not being normalized to `null` as is needed to identify self-reports elsewhere in the app. Fixed this at the `NotificationBuilder` step.
- User has an applet with activity that is set to **Auto-assign: false** and has a **manual self-report assignment**
- Add new scheduled event for activity: 
- Repeats daily
- Notification = in the next 5 minutes (or however long it takes you to refresh and force-close the applet)
**Online mode:**
1. Refresh the applets list to ensure it has the latest updates from the activity (including the notification setting)
2. …
=> fix: Fix clearing of one-time-completion manual self-report assessments from notification (M2-8144, M2-8160)

.github/workflows/ci.yaml, src/entities/applet/model/services/RefreshAppletService.ts, src/shared/api/services/appletsService.ts, src/shared/lib/utils/reactQueryHelpers.ts, src/widgets/activity-group/model/hooks/useBaseInfo.ts
🔗 [Jira Ticket M2-8151](https://mindlogger.atlassian.net/browse/M2-8151)
This PR fixes an issue introduced in https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/873 where the "base info" query data cache is not invalidated, leading to the app crashing after an activity/flow is added to an existing applet.
N/A
1. Create an applet
2. Create an activity
3. Log into the mobile app
4. Go into the activity listing screen
5. Create another activity
6. In the mobile app, go back to the applet listing screen and refresh
7. Go into the activity listing screen
At this point, the app should not crash.
N/A
=> fix: issue with invalidation of applet base info query data (M2-8151)

src/entities/applet/model/slice.ts
🔗 [Jira Ticket M2-8177](https://mindlogger.atlassian.net/browse/M2-8177)
Existing local `in-progress` state for any activity that had a previous submission that same day had fits state reset to `completed` during manual app refresh. Fixed logic to not override the `state` property for these records (previously was being set to `completed`) just because the user has previously submitted the activity that day – rather, just set the `endedAtTimestamp` property if the activity already happened to be in `completed` state, and leave `state` unchanged otherwise.
This bug was introduced when the `applet` slice was changed significantly during the refactor to support MI Assign.
- User is logged in to mobile app
- User has an applet with an activity (auto-assigned or manually assigned) with no …
=> fix: Preserve in-progress state during app refresh (M2-8177)

src/entities/activity/lib/hooks/useQueueProcessing.ts, src/widgets/survey/model/hooks/useAutoCompletion.ts
This PR is the same as https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/887 which was hotfixed into `release/2.5.0` but git did not merge into `dev` even with this [PR](https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/892). 
This re-applies the fix to revert this change https://github.com/ChildMindInstitute/mindlogger-app-refactor/commit/34b9471acb91b26eea684d2722bd7c5670a0d89c. 
N/A
=> fix: Revert "chore: add applets refresh after answers submission" (M2-8144)

android/app/src/main/AndroidManifest.xml
Adds `http` and `https` to AndroidManifest.xml according to [documentation](https://reactnative.dev/docs/linking#canopenurl)
🔗 [Jira Ticket M2-8210](https://mindlogger.atlassian.net/browse/M2-8210)
Tested working using Android simulator
- Build app for Android
- Tap on "Terms" or "Privacy" links from Login screen
- URL should open
=> fix: add http/https to AndroidManifest

src/screens/ui/LoginScreen.tsx
🔗 [Jira Ticket M2-8099](https://mindlogger.atlassian.net/browse/M2-8099)
A change to the footer's styling was added, so that in case a longer text or more items are added to the footer, the overflow/hiding problem won't be present.
This change won't be noticeable from previous instances for now, since the elements as they are right now don't present that issue:
- Updated styling for footer container (inside `LoginScreen.tsx`)
| Before (Optional)                      | After                                 |
| <img width="927" alt="image" src="https://github.com/user-attachments/assets/45fefbdf-bde9-4455-851f-fdd781ffcd7f"> | <img width="951" alt="image" …
=> fix: Fix greek login screen footer elements wrap (M2-8099)

src/features/pass-survey/model/flankerNextStepEvaluator.ts
🔗 [Jira Ticket M2-8103](https://mindlogger.atlassian.net/browse/M2-8103)
When the accuracy or threshold is set to 0, the system continues to repeat the activity even when the user's accuracy is 100%. The issue was caused by a validation check that verifies if a minimum accuracy is specified in the activity configuration. If it's not present, the system proceeds to repeat the practice at the next index. The problem occurs because a minimum accuracy of 0 was being incorrectly interpreted as a lack of minimum accuracy (as if no minimum accuracy was set).
OBSERVATION:
I tested with 1% threshold, 2% ... every other threshold is working properly, that is, its will only repeat in case user accuracy is less than threshold.
Somehow the admin seems to block setup like 0%, but the  accuracy settings …
=> M2-8103: fixing practice repetitions when threshold is equal 0

src/entities/conditional-logic/model/conditions.test.ts, src/entities/conditional-logic/model/conditions.ts
🔗 [Jira Ticket M2-8301](https://mindlogger.atlassian.net/browse/M2-8301)
Fixing, greater than date times range, less than time range, equal to time range and not equal time range.
https://github.com/user-attachments/assets/9718d0bf-d48f-4118-940c-e372fb68e2d4
1 - create an applet with time range conditional logic like this:
2 - launch the app, and check if the conditional logic is responding righ
=> Fix: fixing time range conditions M2-8301 

src/entities/activity/model/mappers.ts
🔗 [Jira Ticket M2-8274](https://mindlogger.atlassian.net/browse/M2-8274)
the drawing item type was shown even when condition not met.
this PR adds the conditional logic mapping to the item
1 - create an activity with some conditional logic that enable and disable Drawing item type
2 - launch the app and check if the drawing item is responding to the conditional logic.
=> adding mapConditionalLogic to drawing item type

src/entities/conditional-logic/model/conditions.ts
🔗 [Jira Ticket M2-8308](https://mindlogger.atlassian.net/browse/M2-8308)
Fixing the logic of isBetweenSliderRow
https://github.com/user-attachments/assets/ee031336-281d-447d-9633-bc5ab0123d63
1 - create an activity with slider per row item and  create a logic of between. ( similar to what I left on screenshots)
2 - launch the app, and check if the Boundary value is considered as a valid response ( example):
between 2 and 4,   the "2" and "4" shouldn't be a valid answer, only "3".
=> fix: M2-8308 fixing isBetweenSliderRowValues logic

src/features/pass-survey/model/AnswerValidator.ts
🔗 [Jira Ticket M2-8294](https://mindlogger.atlassian.net/browse/M2-8294)
Fixing how singleSelectionPerRow get value
https://github.com/user-attachments/assets/1e261093-663f-4a8c-8315-dce9bd235681
1 - create an activity with  single selection per row Item
2 - create a conditional logic (could be any conditional logic as long it is is equal or it is not equal) 
3 - launch the app 
4 - select the applet with the activity you created and check if the logic is responding right.
=> Fix: M2-8294 Single selection per row: The user remains on the input screen after selecting the response and tapping 'Next'

android/app/src/main/AndroidManifest.xml
🔗 [Jira Ticket M2-8444](https://mindlogger.atlassian.net/browse/M2-8444)
It was not possible to allow local notifications.
ERROR:
https://github.com/user-attachments/assets/c0bab2de-2bdc-4665-932b-1ace169e5e7a
FIX:
https://github.com/user-attachments/assets/3c8d9f0f-9f89-40ca-84f1-d8af860f4bc4
1 - Install the app on Android 15, ( it would be good test with previous versions as well)
2 - Allow to use notifications on the first pop-up
=> Fix: M2-8444 Allowing Alarm permission from Android manifest

src/jobs/request-interception.ts
🔗 [Jira Ticket M2-8664](https://mindlogger.atlassian.net/browse/M2-8664)
This PR updates the Axios interceptor to add the following HTTP headers to each request:
- **Device-Id**: The device ID currently sent on sign up or login
- **OS-Name**: `android` or `ios`
- **OS-Version**: The version of the OS (e.g. 13 for Android 13)
- **App-Version**: The version of the MindLogger app currently installed.
When paired with https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1727, the `user_devices` table will now populate these extra properties instead of leaving them blank. This happens on login, so you can use that behaviour to confirm it works
Using https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1727, run the API and log into the MindLogger app. Then …
=> feat: Update mobile app to send device properties on each request (M2-8664)

src/features/pass-survey/model/hooks/useActivityStepper.ts
Adds Group 1 and Group 2 item types to list of valid `ConditionalLogicItems` types
🔗 [Jira Ticket M2-8320](https://mindlogger.atlassian.net/browse/M2-8320)
**Before** - Text item is displayed even when conditional logic shouldn't pass
https://github.com/user-attachments/assets/61285cb6-2335-4f85-b32f-0419f18feea6
**After** - Activity is submitted after conditional logic determines there are no more items available
https://github.com/user-attachments/assets/5cd84c75-0d1a-4f5a-8bab-5bbfab2506a3
- Create an Activity as instructed in the Jira ticket
- Include 3 items: Number Select and 2 others, e.g. Single Select and Text
- Create Conditional logic using Number Select to show Single Select, and Single Select to show Text
- Save
- Start activity in the mobile app
- Answer NumberSelect so that …
=> fix: include additional ItemTypes in ConditionalLogic (M2-8320)

src/entities/activity/lib/services/AnswersUploadService.ts, src/entities/activity/lib/types/uploadAnswers.ts, src/entities/event/lib/types/event.ts, src/entities/event/model/mappers.ts, src/shared/api/services/IAnswerService.ts, src/shared/api/services/IEventsService.ts, src/widgets/survey/model/services/ConstructCompletionsService.ts, src/widgets/survey/model/services/tests/ConstructCompletionsService.test.ts
> [!IMPORTANT]
> For the answer submission to be accepted by the BE, it requires running it with this branch checked out: https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1754
🔗 [Jira Ticket M2-8481](https://mindlogger.atlassian.net/browse/M2-8481)
Adds `eventHistoryId` to new submissions, making sure to use the existing queue service.
- Create a new Applet/Activity
- Submit the activity using the mobile app
- Validate `eventHistoryId` is included in the payload
- You can review the `encryptedData` payload in `AnswersUploadService.uploadAnswers` or by ensuring `event_history_id` is saved in the new answer directly in the database.
=> feat: add event history id to answer submissions (M2-8481)

src/screens/config/theme.tsx, src/shared/ui/Text.tsx, src/widgets/survey/ui/UploadRetryBanner.tsx, src/widgets/survey/ui/completion/ActivityProgressStep.tsx, src/widgets/survey/ui/completion/CircleProgressStep.tsx, src/widgets/survey/ui/completion/ProcessingAnswers.tsx
🔗 [Jira Ticket M2-8800](https://mindlogger.atlassian.net/browse/M2-8800)
🔗 [Jira Ticket M2-8801](https://mindlogger.atlassian.net/browse/M2-8801)
The "Processing Answers" text was being cut off after the recent line height change; this was related to shorthand prop names complicating the default line height calculation.
Also, using the `headerTitle` component affected the default value for `headerBackVisible` on Android only. Fixed by setting it explicitly to `false`.
| Before                      | After                                 | |
| -------------------------------------- | ------------------------------------- | - |
| ![processing answers trim](https://github.com/user-attachments/assets/974c7b88-9541-4ebd-9726-fadeafee7d86) | …
=> fix: Mobile app fixes (M2-8800, M2-8801)

src/features/pass-survey/model/hooks/useActivityStepper.ts
🔗 [Jira Ticket M2-8842](https://mindlogger.atlassian.net/browse/M2-8842)
This fixes a regression introduced by #943 that caused `0` values for Slider items to be interpreted as "no answer", preventing the respondent from being able to proceed to the next step.
1. Create an activity with a Slider item that can accept 0 as a minimum value
2. Log into the mobile app as a respondent.
3. Start the activity.
4. Tap on the min value (0) on the slider range.
- **Before:** It is impossible to proceed with the selected min value ‘0' on slider, and the "Undo" and "Next" buttons don’t appear.
- **After:** It is possible to proceed with the selected min value ‘0' on slider, and the "Undo" and "Next" buttons appear.
**Confirm original fix for #943 continues to work:**
1. Create an Activity as …
=> fix: Treat `0` as valid number answer (M2-8842)

README.md
This PR changes the recommended command from `yarn pods` to `yarn pods:local` in the README and adds a note about why.
N/A
N/A
N/A
=> chore: Add README note about cocoa pod patches

src/jobs/request-interception.ts
🔗 [Jira Ticket M2-8443](https://mindlogger.atlassian.net/browse/M2-8443)
This PR fixes the iOS version being sent to the backend from the mobile app in the `OS-Version` http header.
Pay attention to the `os_version` column
| Before (Optional)                      | After                                 |
| <img width="521" alt="image" src="https://github.com/user-attachments/assets/92144f75-12e8-4130-bddb-5a276e4cc816" /> | <img width="502" alt="image" src="https://github.com/user-attachments/assets/8ad24676-b882-43a5-ae39-3b59bba303c7" /> |
1. Build and run the mobile app on an iOS device, and log in
2. Check the `user_device_events_history` table in the database and look for rows with `ios` as the …
=> fix: Use the correct constant for the iOS version number (M2-8843)

src/entities/banner/ui/Banners.tsx, src/screens/ui/InProgressActivityScreen.tsx, src/shared/lib/constants/index.ts
🔗 [Jira Ticket M2-9402](https://mindlogger.atlassian.net/browse/M2-9402)
This PR fixes a bug that hides the header on several screens on Android 14 and below. The bug was introduced due to a workaround for https://github.com/react-navigation/react-navigation/issues/12608 that did not account for the bug only being present on Android 15+.
> [!NOTE]
> There should be no change for Android versions 15+
| Before                      | After                                 |
| <img width="240px" src="https://github.com/user-attachments/assets/0dc27de9-229d-42bd-a7d9-363f0c90ecac"> | <img width="240px" src="https://github.com/user-attachments/assets/0958a611-6dbf-4b02-9672-f942583fcc9a"> |
| Before …
=> fix: Header cropping on Android 14 and below (M2-9402)

src/shared/lib/markdown/rules.tsx, src/shared/ui/LongTextInput.tsx, src/shared/ui/MarkdownView.tsx, src/shared/ui/SketchCanvas/SketchCanvas.tsx, src/widgets/survey/ui/TimeIsUpModal.tsx
🔗 [Jira Ticket M2-9405](https://mindlogger.atlassian.net/browse/M2-9405)
🔗 [Jira Ticket M2-9409](https://mindlogger.atlassian.net/browse/M2-9409)
🔗 [Jira Ticket M2-9418](https://mindlogger.atlassian.net/browse/M2-9418)
This PR fixes several bugs identified during QA testing of #986. They are:
- M2-9405: [Mobile] Drawing is flashing (draw with finger or apple pencil)
- M2-9409: [Mobile] Markdown heading smaller after upgrading to React Native 0.79
- M2-9418: [Mobile] “Time’s up” pop-up does not display button text after React Native update
It also fixes a vertical align issue with paragraph text items on Android, where the text was center aligned vertically (vs iOS where it is top aligned).
This was fixed using a suggestion from @farmerpaul to replace the path array state variable with a …
=> fix: React Native Upgrade Bug Fixes (M2-9405) (M2-9409) (M2-9418)

src/features/pass-survey/ui/Header.tsx
🔗 [Jira Ticket M2-9412](https://mindlogger.atlassian.net/browse/M2-9412)
🔗 [Jira Ticket M2-9419](https://mindlogger.atlassian.net/browse/M2-9419)
This PR makes a slight change to the way the survey header is laid out to make room for all the elements. Specifically, when an applet has a watermark and/or a long title, it tends to push the exit button off screen. This change fixes that.
| Before                      | After                                 |
| <img width="240px" alt="image" src="https://github.com/user-attachments/assets/d760a3e3-4675-431b-8200-45e5f502076d" /> | <img width="240px" src="https://github.com/user-attachments/assets/4c9540d9-d672-4226-bc66-16571fa70e95"> |
| <img width="240px" …
=> fix: Survey Exit Button Visibility (M2-9412) (M2-9419)

src/features/pass-survey/ui/ActivityItem.tsx
🔗 [Jira Ticket M2-9387](https://mindlogger.atlassian.net/browse/M2-9387)
🔗 [Jira Ticket M2-9336](https://mindlogger.atlassian.net/browse/M2-9336)
Implemented by @farmerpaul 
M2-9387
Fixes an issue where displayed content images were blinking/flickering when tapping on the screen in activities. The image should remain static after interaction. It addresses a performance optimization issue where the component was unnecessarily re-rendering, causing the visual flickering effect.
M2-9336
Via @farmerpaul 
> seems to be a relic from copy-paste when splash screens were introduced ... 2 years ago, but didn’t cause rendering issues until we needed to support multi-step item types (when EHR was introduced)
Changes implemented include:
- Optimized ActivityItem component to prevent unnecessary …
=> fix: Displayed content and splash image blinking (M2-9387, M2-9336)

src/app/ui/AppProvider/NavigationProvider.tsx
🔗 [Jira Ticket M2-9433](https://mindlogger.atlassian.net/browse/M2-9433)
This PR makes two changes to the mobile app deep link behaviour:
1. The path `/ehr-complete` is now handled on iOS and triggers the same behaviour that the `/active-assessment` link does
2. The logic that handles those deep link paths has been patched to prevent an infinite loop when the app is opened by one of them, but there is no in-progress assessment.
Here's a video of the `/ehr-complete` deep linking handling on iOS taken from https://github.com/ChildMindInstitute/mindlogger-web-refactor/pull/640:
https://github.com/user-attachments/assets/a42d10a2-7c49-4b6a-802f-03a900523887
And now here's Android:
https://github.com/user-attachments/assets/09f2cb0e-52a5-4bc0-81dc-e7b1684531d4
1. Edit the …
=> feat: Handle `/ehr-complete` deep link path (M2-9433)

assets/translations/el.json, assets/translations/en.json, assets/translations/es.json, assets/translations/fr.json, assets/translations/pt-br.json, src/entities/localization/lib/setupLocalization.ts, src/shared/lib/types/language.ts, src/shared/lib/utils/dateTime.ts
---
🔗 [Jira Ticket M2-8805](https://mindlogger.atlassian.net/browse/M2-8805)
This PR adds **Portuguese language support** to the mobile app, allowing users to select Portuguese as their preferred application language.
- Added Portuguese translation file (`pt-br.json`) with all translated strings  
- Added `pt` to Language type definition  
- Imported and configured `pt-br.json` in i18n setup  
- Added Portuguese option to the language selection screen  
- Language selection persists in local storage (existing functionality)  
No feature flag required per requirements. Translation provided by a third-party vendor.  
---
| Before | After |
| ------ | ----- |
| Language options: English, Français, ελληνικά, Español | Language options: English, Français, ελληνικά, Español, Português |
| <img …
=> feat(M2-8781): add Portuguese language support to mobile app

src/entities/activity/lib/services/AnswersUploadService.ts, src/entities/activity/lib/services/tests/AnswersUploadService.test.ts, src/entities/activity/lib/types/uploadAnswers.ts, src/shared/api/services/IAnswerService.ts
🔗 [Jira Ticket M2-9658](https://mindlogger.atlassian.net/browse/M2-9658)
This PR builds on top of the work done in the matching [BE PR](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1931) by removing the requirement of a `createdAt` parameter from the answers existence check endpoint. This gets rid of the issue on local dev environments where mobile apps were unable to submit answers successfully.
After the BE PR is merged, this can be merged as well.
If the BE PR hasn't been merged, point local BE to the `fix/M2-9658-remove-created-at-filtering` branch.
Attempt any activity submissions. They should fulfill successfully.
=> fix: Remove createdAt filtering from existence check (M2-9658)

assets/translations/pt-br.json
🔗 [Jira Ticket M2-9713](https://mindlogger.atlassian.net/browse/M2-9713)
Changed "Grego" to "Ελληνικά" when you are looking at the language selections after changing to Portuguese
=> fix: (M2-9713) Greek selection should be in Greek, not in Portuguese 
