ChildMindInstitute/mindlogger-app-refactor

assets/translations/en.json
assets/translations/fr.json
src/features/forgot-password/ui/ForgotPasswordForm.tsx
src/features/login/ui/LoginForm.tsx
src/features/sign-up/model/SignUpFormSchema.ts
src/features/sign-up/ui/SignUpForm.tsx
src/screens/SignUpScreen/index.tsx

https://mindlogger.atlassian.net/browse/ML-339

M2-339: Sign-Up implementation: UI, Model layers with mocks

---

package.json
src/app/theme/index.ts
src/app/theme/tamagui.config.ts
src/features/sign-up/model/SignUpFormSchema.ts
src/features/sign-up/ui/SignUpForm.tsx
src/screens/SignUpScreen/index.tsx
src/screens/index.tsx
src/shared/lib/constants/colors.ts
src/shared/lib/constants/index.ts
src/shared/lib/index.ts
src/shared/ui/form/CheckBoxField.tsx
src/shared/ui/index.tsx
yarn.lock

https://mindlogger.atlassian.net/browse/M2-339

M2 339 signup - switch to tomagui

---

src/app/ui/AppProvider/ReduxProvider.tsx
src/entities/applet/index.ts
src/entities/applet/model/index.ts
src/entities/applet/model/selectors.ts
src/entities/applet/model/slice.ts
src/entities/applet/ui/AppletCard.tsx
src/entities/applet/ui/AppletList.tsx
src/features/applets-refresh/index.ts
src/features/applets-refresh/ui/AppletsRefresh.tsx
src/features/applets-refresh/ui/index.ts
src/screens/AppletsScreen/index.tsx
src/shared/api/services/appletsService.ts

https://mindlogger.atlassian.net/browse/M2-472

M2-472: Add pull-to-refresh for applets: components & model

---

package.json
src/app/ui/AppProvider/ReactQueryProvider.tsx
src/app/ui/AppProvider/ReduxProvider.tsx
src/app/ui/AppProvider/SplashProvider.tsx
src/shared/lib/storages/AsyncStorage.ts
src/shared/lib/storages/createStorage.ts
yarn.lock

https://mindlogger.atlassian.net/browse/M2-521

feat(redux): Added persister

---

assets/translations/en.json
assets/translations/fr.json
src/entities/activity/lib/types/activityListItem.ts
src/entities/activity/ui/TimeStatusRecord.tsx
src/entities/applet/model/hooks/index.ts
src/entities/applet/model/hooks/useInProgressRecord.ts
src/entities/event/api/hooks/index.ts
src/entities/event/api/hooks/useEventQuery.ts
src/entities/event/api/hooks/useEventsQuery.ts
src/entities/event/api/index.ts
src/entities/event/model/mappers.ts
src/features/pass-survey/model/hooks/index.ts
src/features/pass-survey/model/hooks/useIdleTimer.ts
src/features/pass-survey/ui/ActivityItem.tsx
src/features/pass-survey/ui/ActivityStepper.tsx
src/shared/api/services/answerService.ts
src/shared/lib/constants/dateTime.ts
src/shared/lib/index.ts
src/shared/lib/timers/AppTimer.ts
src/shared/ui/TimeRemaining.tsx
src/widgets/activity-group/model/factories/ActivityGroupsBuilder.ts
src/widgets/activity-group/model/hooks/mocks/mocksForItems.ts
src/widgets/activity-group/model/hooks/useActivityGroups.ts
src/widgets/survey/model/hooks/useFlowState.ts
src/widgets/survey/model/hooks/useTimer.ts
src/widgets/survey/model/pipelineBuilder.ts
src/widgets/survey/ui/Finish.tsx
src/widgets/survey/ui/FlowElementSwitch.tsx
src/widgets/survey/ui/FlowSurvey.tsx

M2-1355 M2-1318 event timers

---

src/entities/event/lib/types/scheduledDateCalculator.ts
src/entities/event/model/operations/SheduledDateCalculator.ts
src/entities/notification/lib/services/filterNotifications.ts
src/entities/notification/lib/services/index.ts
src/entities/notification/lib/types/notificationBuilder.ts
src/entities/notification/model/NotificationRefreshService.ts
src/entities/notification/model/factory/NotificationBuilder.ts
src/entities/notification/model/index.ts
src/entities/notification/model/mappers/entities.ts
src/entities/notification/model/mappers/events.ts
src/entities/notification/model/mappers/index.ts
src/features/applets-refresh/model/hooks/useRefreshMutation.ts
src/features/applets-refresh/ui/AppletsRefresh.tsx
src/screens/ui/AppletsScreen.tsx
src/shared/api/services/appletsService.ts
src/shared/api/services/eventsService.ts
src/shared/lib/hooks/useCacheHasData.ts
src/shared/lib/utils/common.ts
src/shared/lib/utils/index.ts
src/shared/lib/utils/reactQueryHelpers.ts
src/shared/ui/TimeRemaining.tsx
src/widgets/activity-group/lib/types/activityGroupsBuilder.ts
src/widgets/activity-group/model/hooks/useActivityGroups.ts

M2-1390: [Mobile] Integrate business logic with infrastructure

M2-1390: [Mobile] Integrate business logic with infrastructure

---

assets/translations/en.json
assets/translations/fr.json
src/features/change-password/model/ChangePasswordFormSchema.ts

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1161

Change-password length validation fix

---

assets/translations/en.json
assets/translations/fr.json
src/app/ui/AppProvider/ReduxProvider.tsx
src/entities/identity/lib/alerts.ts
src/entities/identity/model/slice.ts
src/features/applets-refresh/model/hooks/useRefreshMutation.ts
src/features/logout/model/hooks.ts
src/features/logout/ui/LogoutRowButton.tsx
src/screens/ui/RootNavigator.tsx
src/shared/lib/utils/index.ts
src/shared/lib/utils/networkHelpers.ts
src/shared/lib/utils/reactQueryHelpers.ts
src/widgets/activity-group/lib/types/activityGroupsBuilder.ts
src/widgets/activity-group/model/hooks/mocks/mocksForEntities.ts
src/widgets/activity-group/model/hooks/useActivityGroups.ts
src/widgets/activity-group/model/hooks/useTimer.ts
src/widgets/activity-group/model/mappers.ts
src/widgets/survey/model/hooks/useTimer.ts

M2-1468 [Mobile] Update activity group list every minute
M2-1450 [Mobile] Logout - react query cache clean up
M2-1448 [Mobile] Consider isHidden activities and flows in activity groups list

M2-1468 M2-1450 M2-1448

---

assets/translations/en.json
src/entities/applet/model/mappers.ts
src/entities/applet/ui/AppletList.tsx
src/features/change-language/ui/ChangeLanguageSelector.tsx
src/features/change-password/ui/ChangePasswordForm.tsx
src/features/sign-up/validation/SignUpFormSchema.ts
src/screens/ui/ChangeLanguageScreen.tsx
src/screens/ui/RootNavigator.tsx
src/shared/lib/constants/colors.ts
src/shared/ui/form/InputField.tsx

https://mindlogger.atlassian.net/browse/M2-1153?search_id=f95b0ccc-1c2e-4bbb-9c3e-51284318b9fb
https://mindlogger.atlassian.net/browse/M2-1144?search_id=86f06e4c-ca15-4cca-ada7-f26815183cb0
https://mindlogger.atlassian.net/browse/M2-1155?search_id=6d29c66a-3549-4d73-a70a-c037c9cbe91c
https://mindlogger.atlassian.net/browse/M2-1158?search_id=f76fb422-0131-45d9-b85e-24b04459ebec

M2-1153 M2-1144 M2-1155 M2-1158

---

assets/translations/en.json
assets/translations/fr.json
src/features/login/model/LoginFormSchema.ts

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1150

fix: login validation message issue

---

src/features/change-language/ui/ChangeLanguageSelector.tsx
src/features/pass-survey/ui/ActivityItem.tsx
src/screens/ui/ChangeLanguageScreen.tsx
src/shared/ui/ScrollableContent.tsx
src/shared/ui/index.tsx

https://mindlogger.atlassian.net/browse/M2-1548
https://mindlogger.atlassian.net/browse/M2-1501

M2-1548 M2-1501

---

assets/translations/en.json
assets/translations/fr.json
src/entities/activity/lib/types/activity.ts
src/entities/activity/model/mappers.ts
src/features/change-password/model/ChangePasswordFormSchema.ts
src/features/pass-survey/lib/types/activityItem.ts
src/features/pass-survey/lib/types/payload.ts
src/features/pass-survey/lib/types/pipelineItemAnswer.ts
src/features/pass-survey/model/hooks/useActivityStepper.ts
src/features/pass-survey/model/pipelineBuilder.ts
src/features/pass-survey/ui/ActivityItem.tsx
src/features/sign-up/validation/SignUpFormSchema.ts
src/screens/ui/RootNavigator.tsx
src/shared/lib/markDownRules.tsx
src/shared/ui/Slider.tsx
src/shared/ui/survey/MarkdownMessage.tsx

https://mindlogger.atlassian.net/browse/M2-1150
https://mindlogger.atlassian.net/browse/M2-1548
https://mindlogger.atlassian.net/browse/M2-1501

Sync with dev

---

src/features/applets-refresh/model/hooks/useRefreshMutation.ts
src/features/change-password/ui/ChangePasswordForm.tsx
src/features/forgot-password/ui/ForgotPasswordForm.tsx
src/features/login/ui/LoginForm.tsx
src/features/sign-up/ui/SignUpForm.tsx
src/shared/lib/alerts/index.ts
src/shared/lib/alerts/networkAlert.ts
src/shared/lib/utils/networkHelpers.ts

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1114

M2 1114 fix missing network alert

---

src/features/pass-survey/ui/ActivityStepper.tsx
src/screens/ui/InProgressActivityScreen.tsx
src/widgets/survey/ui/FlowElementSwitch.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1556

fix(survey_items): statusbar overlap issue

---

src/features/pass-survey/ui/ActivityItem.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1603

refactor(survey_items): add variables replacer to activity item question

---

src/shared/ui/ViewSlider.tsx

https://mindlogger.atlassian.net/browse/M2-1595

fix(survey_items): activity item exit animation

---

src/app/ui/AppProvider/index.tsx
src/entities/localization/index.ts
src/entities/localization/lib/LocalizationStorage.ts
src/entities/localization/lib/index.ts
src/entities/localization/lib/setupLocalization.ts
src/entities/localization/ui/LocalizationProvider.tsx
src/entities/localization/ui/index.ts
src/features/change-language/index.ts
src/features/change-language/ui/index.ts
src/jobs/localization.ts

https://mindlogger.atlassian.net/browse/M2-1646

feat(localization): Added language persistor

---

assets/translations/en.json
assets/translations/fr.json
src/entities/notification/model/factory/NotificationBuilder.ts

According to requirements, Actitivity related notifications must have "Please complete this activity" description. https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/49381410/US-6.1+-+Activity+related+Notifications
https://mindlogger.atlassian.net/browse/M2-1815

fix(notification): Set default notification description text

---

src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts

https://mindlogger.atlassian.net/browse/M2-1810
https://mindlogger.atlassian.net/browse/M2-1813

M2-1810 M2-1813

---

ios/MindloggerMobile.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
src/screens/config/theme.tsx
src/shared/lib/constants/index.ts
yarn.lock

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1257

fix(survey_items): fix tablet view for the app

---

src/shared/lib/permissions/cameraPermissions.ts
src/shared/lib/permissions/galleryPermissions.ts
src/shared/ui/survey/MediaItems/PhotoItem.tsx
src/shared/ui/survey/MediaItems/VideoItem.tsx

https://mindlogger.atlassian.net/browse/M2-1891
https://mindlogger.atlassian.net/browse/M2-1883

fix(permissions): fix photo and video permissions m2-1891 m2-1883

---

src/shared/ui/survey/StackedItemsGrid/StackedItemsGrid.tsx
src/shared/ui/survey/StackedRadiosItem.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1940

fix(survey_items): stacked radio answer handler

---

src/entities/drawer/lib/utils/helpers.ts
src/entities/event/model/operations/SheduledDateCalculator.ts
src/shared/lib/hooks/useUndoClicked.ts

M2-2025, M2-1895

---

src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1942

fix(survey_items): video display in message item

---

src/shared/ui/survey/MediaItems/MediaInput.tsx
src/shared/ui/survey/MediaItems/PhotoItem.tsx
src/shared/ui/survey/MediaItems/VideoItem.tsx

fix(survey_items): border color for media input item when media is selected
https://mindlogger.atlassian.net/browse/M2-1904

fix(survey_items): border color for media input item when media is selected

---

src/abstract/lib/types/index.ts
src/abstract/lib/types/storage.ts
src/entities/applet/model/hooks/useStartEntity.ts
src/features/pass-survey/lib/services/MediaFilesCleaner.ts
src/features/pass-survey/lib/services/index.ts
src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
src/screens/ui/RootNavigator.tsx
src/widgets/activity-group/ui/ActivityGroup.tsx

https://mindlogger.atlassian.net/browse/M2-2143

M2-2143: [Mobile] Clean-up media resources on restart activity

---

src/abstract/lib/types/entityProgress.ts
src/abstract/lib/utils/progressConvert.ts
src/entities/applet/model/slice.ts
src/features/pass-survey/model/AnswerValidator.ts
src/shared/ui/survey/MediaItems/MediaInput.tsx
src/shared/ui/survey/StackedItemsGrid/StackedItemsGrid.tsx
src/widgets/activity-group/model/hooks/mocks/mocksForEntities.ts
src/widgets/survey/model/mappers.ts
src/widgets/survey/model/operations.ts
src/widgets/survey/ui/Finish.tsx
src/widgets/survey/ui/Intermediate.tsx

https://mindlogger.atlassian.net/browse/M2-2128

Migrate answers to legacy dto

---

ios/MindloggerMobile.xcodeproj/project.pbxproj
src/shared/lib/constants/index.ts
src/shared/lib/permissions/cameraPermissions.ts
src/shared/lib/permissions/galleryPermissions.ts
src/shared/ui/survey/MediaItems/PhotoItem.tsx
src/shared/ui/survey/MediaItems/VideoItem.tsx

https://mindlogger.atlassian.net/browse/M2-2292 https://mindlogger.atlassian.net/browse/M2-2278  https://mindlogger.atlassian.net/browse/M2-1887

Fix android permissions for media items

---

src/shared/ui/DateTimePicker.tsx

https://mindlogger.atlassian.net/browse/M2-2076

fix(survey_items): time picker appearance issue

---

src/shared/lib/hooks/useMicrophonePermissions.ts
src/shared/lib/permissions/microphonePermissions.ts
src/shared/ui/survey/AudioRecorderItem.tsx

https://mindlogger.atlassian.net/browse/M2-2324, https://mindlogger.atlassian.net/browse/M2-2326

fix(survey_items): audio item permissions

---

src/shared/ui/survey/AudioRecorderItem.tsx

https://mindlogger.atlassian.net/browse/M2-2326

fix(survey_items): audio recording display

---

src/abstract/lib/types/index.ts
src/abstract/lib/types/primitive.ts
src/entities/abTrail/lib/types/test.ts
src/entities/abTrail/lib/utils/calculation.ts
src/entities/abTrail/ui/AbCanvas.tsx
src/entities/abTrail/ui/AbShapes.tsx
src/entities/activity/api/useActivityAnswersMutation.ts
src/entities/drawer/lib/types/draw.ts
src/entities/drawer/lib/utils/bezier.ts
src/entities/drawer/ui/DrawingBoard.tsx
src/entities/drawer/ui/DrawingTest.tsx
src/features/pass-survey/ui/ActivityItem.tsx
src/shared/api/services/answerService.ts
src/shared/api/services/fileService.ts
src/shared/ui/survey/MediaItems/types.ts
src/widgets/survey/model/mappers.ts

https://mindlogger.atlassian.net/browse/M2-2359
https://mindlogger.atlassian.net/browse/M2-2346
Drawer & Flanker - map responses to old format

M2-2346 M2-2359

---

src/entities/drawer/ui/DrawingBoard.tsx
src/entities/drawer/ui/DrawingTest.tsx
src/features/pass-survey/lib/contexts/ActivityScrollContext.ts
src/features/pass-survey/lib/contexts/index.ts
src/features/pass-survey/ui/ActivityItem.tsx
src/shared/ui/ScrollableContent.tsx

Also added fixes for https://mindlogger.atlassian.net/browse/M2-2410

M2 2188 drawing item

---

src/entities/activity/lib/services/MediaFilesCleaner.ts
src/features/pass-survey/model/AnswerValidator.ts
src/features/pass-survey/model/PipelineVisibilityChecker.ts

https://mindlogger.atlassian.net/browse/M2-2425

fix(conditional_logic): not icludes operation

---

src/widgets/survey/model/mappers.ts

https://mindlogger.atlassian.net/browse/M2-2416

fix(survey_items): checkbox reselect issue

---

ios/MindloggerMobile dev-Info.plist
ios/MindloggerMobile qa-Info.plist
ios/MindloggerMobile staging-Info.plist
ios/MindloggerMobile/Info.plist

The changes have been made due to the build problem that refered to missing orientations: https://app.bitrise.io/build/fc979515-b603-47fc-a087-46f571190282

fix(ios): Added all iPad orientations

---

src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/browse/M2-1942

fix(survey_items): media message video formats

---

src/shared/ui/RoundLogo.tsx

https://mindlogger.atlassian.net/browse/M2-2469

fix(applets): display image url with whitespaces

---

src/app/ui/AppProvider/ReactQueryProvider.tsx

https://mindlogger.atlassian.net/browse/M2-2558

fix(applets): react query persist period

---

src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/browse/M2-2618

fix(survey_items): message item video content app crash

---

src/entities/drawer/lib/utils/helpers.ts
src/entities/drawer/lib/utils/serialization.tsx
src/entities/drawer/ui/DrawingBoard.tsx

https://mindlogger.atlassian.net/browse/M2-2633

M2-2633: [Mobile app] Data Export: Drawing canvas is not 100x100

---

android/app/build.gradle
android/build.gradle
firebase.json
ios/Podfile.lock
package.json
src/screens/ui/AppletsScreen.tsx
yarn.lock

Integration with Firebase Crashlytics

Experiment crashlytics ios

---

src/shared/lib/constants/index.ts

https://mindlogger.atlassian.net/browse/M2-2417

fix(media): Added fullscreen view to media item picker

---

src/entities/drawer/ui/DrawingBoard.tsx
src/entities/drawer/ui/DrawingTest.tsx

https://mindlogger.atlassian.net/browse/M2-1895
https://mindlogger.atlassian.net/browse/M2-1979

M2 1979, M2 1895 drawer issues

---

src/entities/flanker/lib/utils/helpers.ts

https://mindlogger.atlassian.net/browse/M2-2794
https://mindlogger.atlassian.net/browse/M2-2795

M2-2794, M2-2795 Flanker issues

---

src/entities/activity/model/mappers.ts

https://mindlogger.atlassian.net/browse/M2-2858

fix(alerts): mapper for data matrix

---

src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/browse/M2-2828

fix(survey_items): added container for table markdown view

---

src/features/pass-survey/model/hooks/useUserActionManager.ts
src/features/pass-survey/model/precompiled-pipelines.ts
src/features/pass-survey/ui/ActivityStepper.tsx

https://mindlogger.atlassian.net/browse/M2-2791
https://mindlogger.atlassian.net/browse/M2-2791

fixes for M2-2791, M2-2792 - user actions for ab trails

---

ios/FlankerNativeComponents/FlankerView.swift
ios/FlankerNativeComponents/ImageLoader.swift
ios/FlankerNativeComponents/UIImageView+Extensions.swift

https://mindlogger.atlassian.net/browse/M2-2905

fix(flanker): resize image buttons and primary image

---

src/shared/ui/survey/StackedCheckboxItem/StackedCheckboxItem.tsx

https://mindlogger.atlassian.net/browse/M2-2234

fix(survey_items): checkbox check area

---

src/shared/lib/constants/colors.ts
src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/browse/M2-2808

fix(survey_items): code text styles for display content

---

src/features/sign-up/model/hooks/useRegistrationMutation.ts

https://mindlogger.atlassian.net/browse/M2-2879
https://mindlogger.atlassian.net/browse/M2-2890

Fixes for M2-2879, M2-2890

---

src/widgets/survey/model/mappers.ts

https://mindlogger.atlassian.net/browse/M2-2797

fix(CST): Changed report names according to phase type

---

src/widgets/activity-group/model/factories/ActivityGroupsBuilder.ts

https://mindlogger.atlassian.net/browse/M2-3089

fix for M2-3089: [Mobile app] The activity timer issue

---

src/entities/applet/model/mappers.ts
src/features/pass-survey/lib/hooks/useTextVariablesReplacer.ts
src/features/pass-survey/ui/ActivityStepper.tsx
src/shared/api/services/appletsService.ts

https://mindlogger.atlassian.net/browse/M2-2943

fix(survey_items): nickname display in variable replacer

---

src/features/pass-survey/ui/ActivityItem.tsx

https://mindlogger.atlassian.net/browse/M2-2415

fix(survey_items): margins for items when content text too big

---

src/entities/activity/lib/services/AnswersUploadService.ts
src/shared/lib/utils/file.ts
src/shared/lib/utils/index.ts
src/shared/ui/survey/AudioRecorderItem.tsx

https://mindlogger.atlassian.net/browse/M2-3446

fix(survey_items): audio item file check

---

src/entities/notification/model/factory/NotificationBuilder.ts

https://mindlogger.atlassian.net/browse/M2-3197

M2-3197: Update the text in push notification for Reminder

---

src/shared/ui/HorizontalCalendar.tsx

https://mindlogger.atlassian.net/browse/M2-3521

fix(applets): spacing for calendar

---

src/entities/applet/model/mappers.ts

https://mindlogger.atlassian.net/browse/M2-3583

fix(applets): applet opening

---

src/entities/abTrail/ui/AbCanvas.tsx
src/entities/abTrail/ui/AbShapes.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-1979

Fixed M2-1979 drawing and AbTrails blinking issue

---

src/screens/ui/AppletBottomTabNavigator.tsx

https://mindlogger.atlassian.net/browse/M2-3675

fix(survey_items): theme logo in header on applet details screen

---

assets/translations/en.json
assets/translations/fr.json
src/entities/applet/lib/alerts.ts
src/entities/applet/model/hooks/useRefreshMutation.ts
src/entities/applet/model/services/RefreshService.ts
src/entities/notification/model/NotificationRefreshService.ts
src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
src/screens/ui/RootNavigator.tsx
src/shared/lib/services/collectImageUrls.ts
src/widgets/activity-group/model/hooks/useActivityGroups.ts
src/widgets/activity-group/model/services/ActivityGroupsBuildManager.ts
src/widgets/activity-group/ui/ActivityGroupList.tsx

https://mindlogger.atlassian.net/browse/M2-3808

M2-3808: Manage kill app during refresh process

---

src/features/pass-survey/lib/types/userAction.ts
src/features/pass-survey/model/hooks/useUserActionCreator.ts
src/features/pass-survey/ui/ActivityStepper.tsx
src/shared/api/services/answerService.ts

https://mindlogger.atlassian.net/browse/M2-3832

fix(activities): skip action

---

src/entities/applet/model/services/RefreshService.ts
src/entities/notification/model/NotificationRefreshService.ts

https://mindlogger.atlassian.net/browse/M2-2847

M2-2847: added some logs, minor changes

---

assets/translations/en.json
assets/translations/fr.json
src/features/sign-up/ui/SignUpForm.tsx
src/screens/ui/RootNavigator.tsx
src/screens/ui/SignUpScreen.tsx
src/shared/ui/icons/index.tsx

feat: added new UI for creating account screen

---

ios/Podfile.lock
package.json
src/app/ui/AppProvider/ReactQueryProvider.tsx
src/app/ui/AppProvider/ReduxProvider.tsx
src/app/ui/AppProvider/SplashProvider.tsx
src/app/ui/AppProvider/SystemBootUpProvider.tsx
src/app/ui/AppProvider/index.tsx
src/shared/lib/contexts/SplashContext.ts
src/shared/ui/Splash.tsx
yarn.lock

Fixes:
https://mindlogger.atlassian.net/browse/M2-1685
https://mindlogger.atlassian.net/browse/M2-4029
1. Updated reanimated package.
2. Make the app render either Splash screen or App content but not together. After all code optimization that have been made the app booted up too fast causing conflicts on certain parts of the code, e.g. it addressed the state's objects that weren't fully hydrated.

M2-1685 and M2-4029

---

src/entities/notification/model/factory/NotificationBuilder.ts

https://mindlogger.atlassian.net/browse/M2-3179

M2-3179: [Mobile] Daily event: Reminder notification doesn't come

---

src/screens/ui/AppletsScreen.tsx

https://mindlogger.atlassian.net/browse/M2-4068

fix(applets): retry banner on applets screen

---

src/features/sign-up/ui/SignUpForm.tsx
src/features/sign-up/validation/SignUpFormSchema.ts

Resolves:
https://mindlogger.atlassian.net/browse/M2-4212

fix(hotfix): sign up terms validation

---

src/features/pass-survey/ui/ActivityStepper.tsx

https://mindlogger.atlassian.net/browse/M2-4143

fix(survey_items): stepper height

---

src/widgets/activity-group/ui/ActivitySectionList.tsx

Fixed M2-3979, checking if the screen is still focused before navigating to InProgressActivity screen
[M2-3979](https://mindlogger.atlassian.net/browse/M2-3979)

Fixed M2-3979

---

src/features/pass-survey/lib/types/payload.ts
src/features/pass-survey/model/AlertsExtractor.ts

Fixed [M2-4067](https://mindlogger.atlassian.net/browse/M2-4072), checking if slider value is null, bugfix for continous slider

Fixed M2-4067, checking if slider value is null

---

src/features/pass-survey/ui/ActivityItem.tsx

https://mindlogger.atlassian.net/browse/M2-4140

fix(survey_items): added delay to radio button press

---

src/entities/activity/lib/services/AnswersUploadService.ts

Fixed [M2-4130](https://mindlogger.atlassian.net/browse/M2-4130), Adding additional text to user actions for media files

Fixed M2-4130, Adding additional text to user actions for media files

---

src/features/pass-survey/ui/ActivityItem.tsx
src/shared/ui/survey/RadioActivityItem/RadioActivityItem.tsx

https://mindlogger.atlassian.net/browse/M2-4233
https://mindlogger.atlassian.net/browse/M2-4231

Fix(m2-4231, m2-4233) fix radio item delay issues

---

assets/translations/en.json
assets/translations/fr.json
src/shared/lib/constants/index.ts
src/shared/ui/charts/BarChart/BarChart.tsx
src/shared/ui/charts/LineChart/LineChart.tsx
src/shared/ui/charts/TimelineChart/TimelineChart.tsx
src/shared/ui/charts/lib/getWeekDaysWithLocale.ts
src/shared/ui/charts/lib/index.ts

Fixed [M2-3502](https://mindlogger.atlassian.net/browse/M2-3502) french language translations for week day names in activity data tab

Fixed M2-3502 french language translations for week day names

---

src/shared/ui/survey/MediaItems/PhotoItem.tsx

Apparently replacing HEIC with JPG is enough to make conversion: https://stackoverflow.com/a/68651864
https://mindlogger.atlassian.net/browse/M2-4242

fix(media): Replace HEIC image with JPG

---

src/entities/drawer/ui/DrawingTest.tsx
src/widgets/survey/model/operations.ts
src/widgets/survey/ui/Finish.tsx
src/widgets/survey/ui/Intermediate.tsx

Fixes:
https://mindlogger.atlassian.net/browse/M2-4260

fix(drawing): Moved SVG creation from activity item to the end of activity

---

src/shared/ui/SketchCanvas/LineSketcher.ts
src/shared/ui/SketchCanvas/SketchCanvas.tsx

[M2-4243](https://mindlogger.atlassian.net/browse/M2-4243)
[M2-4243]: https://mindlogger.atlassian.net/browse/M2-4243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed M2-4243 drawer dot issue, preventing drawing the same point multiple times

---

src/shared/ui/survey/RadioActivityItem/RadioActivityItem.tsx

https://mindlogger.atlassian.net/browse/M2-4287

fix(M2-4287): undo action for radio item

---

src/widgets/survey/ui/FlowElementSwitch.tsx

Fixes:
https://mindlogger.atlassian.net/browse/M2-4269

fix(activity-stepper): Close activity stepper by just navigating back without extra actions

---

src/shared/ui/survey/Geolocation/GeolocationItem.tsx

Fixed [M2-4263 ](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4263) geolocation while offline issue
[getCurrentPosition documentation](https://github.com/michalchudziak/react-native-geolocation#getcurrentposition)

Fixed M2-4263 geolocation while offline issue

---

ios/FlankerNativeComponents/FlankerView.swift
ios/FlankerNativeComponents/FlankerViewManager.m
ios/FlankerNativeComponents/FlankerViewManager.swift
ios/FlankerNativeComponents/ImageLoader.swift
ios/FlankerNativeComponents/ParameterGameManager.swift
src/entities/flanker/ui/NativeIosFlanker/NativeIosFlanker.tsx

https://mindlogger.atlassian.net/browse/M2-4165

fix(survey_items): flanker image cache

---

src/shared/lib/constants/index.ts
src/shared/ui/ScrollableContent.tsx

Fixed [M2-4254](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4254) scroll issue on small viewports
[M2-4254]: https://mindlogger.atlassian.net/browse/M2-4254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed M2-4254 scroll issue on small viewports

---

ios/FlankerNativeComponents/FlankerView.swift
ios/FlankerNativeComponents/GameManager.swift

https://mindlogger.atlassian.net/browse/M2-4343

fix(flanker): different flanker buttons case

---

src/entities/notification/lib/types/notificationBuilder.ts
src/entities/notification/model/factory/NotificationBuilder.ts
src/entities/notification/model/factory/NotificationDaysExtractor.ts
src/entities/notification/model/factory/NotificationUtility.ts
src/entities/notification/model/factory/ReminderCreator.ts

https://mindlogger.atlassian.net/browse/M2-4350

M2 4350 reminder is not receiving

---

src/features/pass-survey/ui/ActivityItem.tsx
src/shared/ui/survey/CheckBox/CheckBox.item.tsx
src/shared/ui/survey/CheckBox/CheckBoxActivity.item.tsx
src/shared/ui/survey/RadioActivityItem/RadioActivityItem.tsx
src/shared/ui/survey/RadioActivityItem/RadioItem.tsx
src/shared/ui/survey/Slider/SurveySlider.tsx

https://mindlogger.atlassian.net/browse/M2-4142
iOS
Android

M2 4142 images styles enhancement

---

ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/entities/applet/model/services/RefreshService.ts
src/shared/api/services/answerService.ts
src/shared/api/services/fileService.ts
src/shared/lib/utils/networkHelpers.ts
yarn.lock

https://mindlogger.atlassian.net/browse/M2-4339

M2 4339 handle network error

---

ios/Podfile.lock
package.json
yarn.lock

https://mindlogger.atlassian.net/browse/M2-4145

M2-4145 - fix: update reanimated library to fix issue with intermidiate screen overlay

---

src/shared/lib/utils/dateTime.ts
src/shared/ui/survey/DatePickerItem.tsx
src/widgets/survey/model/mappers.ts

Fixed [4348](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4348), ignoring timezone when converting DatePicker value to Date

Fixed 4348, ignoring timezone when converting DatePicker value to Date

---

src/shared/lib/markDownRules.tsx

[4332](https://mindlogger.atlassian.net/browse/M2-4332)

Fixed 4332 markdown styling

---

assets/translations/en.json
assets/translations/fr.json
src/shared/lib/hooks/useAudioPlayer.ts
src/shared/ui/survey/AudioStimulusItem.tsx

[M2-4296](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4296) audio player, showing loader , when loading the audio file, code and ui improvement.
[M2-4296]: https://mindlogger.atlassian.net/browse/M2-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-4296 audio player, showing loader , when loading the audio

---

src/entities/activity/ui/ActivityCard.tsx
src/entities/activity/ui/ActivityList.tsx
src/entities/applet/ui/AppletCard.tsx
src/entities/applet/ui/AppletList.tsx
src/features/pass-survey/ui/ActivityStepper.tsx
src/screens/config/theme.tsx
src/screens/ui/RootNavigator.tsx
src/widgets/activity-group/ui/ActivitySectionList.tsx
src/widgets/survey/ui/Finish.tsx

https://mindlogger.atlassian.net/browse/M2-3110

refactor: added changes for auto test: new attributes and refactoring

---

src/features/sign-up/model/hooks/useRegistrationMutation.ts
src/shared/lib/analytics/AnalyticsService.ts
src/shared/lib/analytics/MixpanelAnalytics.ts

[M2-4418](https://mindlogger.atlassian.net/browse/M2-4418)
[M2-4418]: https://mindlogger.atlassian.net/browse/M2-4418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mixpanel events updates 4418

---

src/shared/ui/survey/Slider/SurveySlider.tsx

[M2-4142](https://mindlogger.atlassian.net/browse/M2-4142)
[M2-4142]: https://mindlogger.atlassian.net/browse/M2-4142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-4142 slider item ui fixes

---

src/entities/notification/model/factory/NotificationDaysExtractor.test.ts
src/entities/notification/model/factory/NotificationDaysExtractor.ts
src/widgets/activity-group/model/factories/ActivityGroupsBuilder.test.ts

https://mindlogger.atlassian.net/browse/M2-4303
https://mindlogger.atlassian.net/browse/M2-4484

M2-4303, M2-4484 - unit tests

---

ios/FlankerNativeComponents/CustomButton.swift

https://mindlogger.atlassian.net/browse/M2-4416

fix(flanker): fix button press visibility for flanker buttons

---

src/shared/ui/survey/MediaItems/MediaInput.tsx

https://mindlogger.atlassian.net/browse/M2-1904

fix(survey_items): rounded corners of media items

---

src/entities/notification/lib/services/NotificationsLogger.ts
src/entities/notification/model/factory/NotificationBuilder.ts
src/entities/notification/model/factory/NotificationUtility.ts
src/entities/notification/model/factory/tests/NotificationDaysExtractor.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.getRandomBorderType.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.getTriggerAt.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.weekDays.test.ts
src/shared/api/services/notificationService.ts

https://mindlogger.atlassian.net/browse/M2-4552
https://mindlogger.atlassian.net/browse/M2-4554
https://mindlogger.atlassian.net/browse/M2-4571
https://mindlogger.atlassian.net/browse/M2-4492

M2-4552, M2-4554, M2-4571, M2-4492: Notifications: unit tests, logs integration

---

src/entities/activity/ui/ActivityCard.tsx
src/entities/activity/ui/ActivityList.tsx
src/features/pass-survey/ui/ActivityItem.tsx
src/shared/ui/survey/Geolocation/GeolocationItem.tsx
src/shared/ui/survey/Slider/StackedSlider.tsx
src/shared/ui/survey/Slider/SurveySlider.tsx
src/shared/ui/survey/StackedCheckboxItem/StackedCheckboxItem.tsx
src/shared/ui/survey/StackedItemsGrid/StackedItemsGrid.tsx
src/shared/ui/survey/StackedRadiosItem.tsx
src/widgets/activity-group/ui/ActivitySectionList.tsx
src/widgets/survey/ui/Finish.tsx

https://mindlogger.atlassian.net/browse/M2-3110

feat(survey_items): added enhancements for auto test attributes

---

src/entities/notification/model/factory/NotificationUtility.ts
src/entities/notification/model/factory/tests/NotificationUtility.getAvailabilityInterval.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.markAsInactive.test.ts

https://mindlogger.atlassian.net/browse/M2-4579
https://mindlogger.atlassian.net/browse/M2-4581

Add unit tests for NotificationUtility: M2-4579, M2-4581

---

src/shared/ui/Stepper/NextButton.tsx
src/shared/ui/Tooltip.tsx
src/shared/ui/survey/CheckBox/CheckBox.item.tsx
src/shared/ui/survey/RadioActivityItem/RadioItem.tsx
src/shared/ui/survey/StackedItemsGrid/StackedItemsGrid.tsx
src/shared/ui/survey/StackedItemsGrid/types.ts

https://mindlogger.atlassian.net/browse/M2-4694
https://mindlogger.atlassian.net/browse/M2-4693
https://mindlogger.atlassian.net/browse/M2-4573

M2-4573, M2-4693, M2-4694: Add unique attributes

---

src/shared/ui/SketchCanvas/SketchCanvas.tsx
src/shared/ui/SketchCanvas/TouchInfoMatrix.ts

https://mindlogger.atlassian.net/browse/M2-4728

fix(drawing): Stopped handling multi-touches

---

assets/translations/en.json
assets/translations/fr.json
src/features/change-password/ui/ChangePasswordForm.tsx
src/shared/lib/utils/dateTime.ts
src/shared/ui/MarkdownView.tsx
src/shared/ui/survey/MediaItems/PhotoItem.tsx
src/shared/ui/survey/MediaItems/VideoItem.tsx

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4524 fixed translation , date format function and MarkdownView todos left

M2-4524 fixed translation , date format function and MarkdownView todos

---

src/shared/lib/services/collectImageUrls.test.ts

https://mindlogger.atlassian.net/browse/M2-4530

Unit tests for collectImageUrls functions

---

src/shared/lib/services/Logger.test.ts

https://mindlogger.atlassian.net/browse/M2-3848

Unit tests for Logger service

---

src/shared/lib/markDownRules.tsx

https://mindlogger.atlassian.net/browse/M2-4488

fix(markdown): Added spaces when content is aligned

---

src/features/pass-survey/ui/ActivityItem.tsx
src/shared/ui/survey/StackedCheckboxItem/StackedCheckboxItem.tsx
src/shared/ui/survey/StackedRadiosItem.tsx

https://mindlogger.atlassian.net/browse/M2-4763

fix(stacked-items): Added conditional rendering for tooltips

---

src/entities/notification/lib/types/notificationBuilder.ts
src/entities/notification/model/factory/NotificationBuilder.ts
src/entities/notification/model/factory/NotificationUtility.ts
src/entities/notification/model/factory/tests/NotificationBuilder.processEvent.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.markAsInactive.test.ts

https://mindlogger.atlassian.net/browse/M2-4582

M2-4582 unit tests process event

---

src/shared/lib/encryption/encryption.test.js
src/shared/lib/encryption/encryption.ts

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4879
encryption service encrypt function optimization

fix(drawing) M2-4879: encryption service encrypt function optimization

---

jest.setup.js
src/entities/notification/model/factory/NotificationUtility.ts
src/entities/notification/model/factory/tests/NotificationBuilder.alwaysAvailable.test.ts
src/entities/notification/model/factory/tests/NotificationBuilder.daily.test.ts
src/entities/notification/model/factory/tests/NotificationBuilder.processEvent.test.ts
src/entities/notification/model/factory/tests/NotificationBuilder.processEventDay.test.ts
src/entities/notification/model/factory/tests/NotificationBuilder.weekly.test.ts
src/entities/notification/model/factory/tests/NotificationDaysExtractor.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.getAvailabilityInterval.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.getRandomBorderType.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.getTriggerAt.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.markAsInactive.test.ts
src/entities/notification/model/factory/tests/NotificationUtility.weekDays.test.ts
src/entities/notification/model/factory/tests/testHelpers.ts

https://mindlogger.atlassian.net/browse/M2-4583
https://mindlogger.atlassian.net/browse/M2-4584
https://mindlogger.atlassian.net/browse/M2-4585
https://mindlogger.atlassian.net/browse/M2-4586

M2-4583, M2-4584, M2-4585, M2-4586: Unit tests for NotificationBuilder

---

src/shared/ui/SketchCanvas/SketchCanvas.tsx

https://mindlogger.atlassian.net/browse/M2-4932

fix(drawing): Added callbacks memoization for performace reasons

---

src/entities/applet/lib/hooks/useAppletAnalytics.ts
src/shared/lib/utils/dateTime.ts

https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4854
updated the date that we are sending to backend, to the start of the day instead of now.

M2-4854: data-tab updated the date that we are sending to backend

---

src/shared/ui/SketchCanvas/CanvasBoard.tsx
src/shared/ui/SketchCanvas/SketchCanvas.tsx

https://mindlogger.atlassian.net/browse/M2-4932

fix(drawing): Moved canvas to a separate stateful component for performace reasons

---

src/entities/event/model/operations/ScheduledDateCalculator.test.js
src/features/pass-survey/model/tests/ScoresCalculator.collectMaxScores.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForCheckboxes.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForItem.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForRadio.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForSlider.test.ts
src/shared/lib/encryption/encryption.test.js
src/shared/lib/encryption/encryption.ts

https://mindlogger.atlassian.net/browse/M2-4910
https://mindlogger.atlassian.net/browse/M2-4909
https://mindlogger.atlassian.net/browse/M2-4911
https://mindlogger.atlassian.net/browse/M2-5039
https://mindlogger.atlassian.net/browse/M2-4912

M2-4910, M2-4909, M2-4908, M2-5039, M2-4911, M2-4912: [Mobile] Unit tests for ScoresCalculator, fixes in some other tests

---

src/features/pass-survey/model/ScoreConditionsEvaluator.ts
src/features/pass-survey/model/tests/ScoreConditionsEvaluator.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.calculate.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectMaxScores.test.ts
src/features/pass-survey/model/tests/ScoresCalculator.collectScoreForRadio.test.ts

https://mindlogger.atlassian.net/browse/M2-4913
https://mindlogger.atlassian.net/browse/M2-4914

M2-4913, M2-4913: Unit tests for Scores Calculator

---

src/shared/ui/NoListItemsYet.tsx
src/shared/ui/form/InputField.tsx

🔗 [Jira Ticket M2-4898](https://mindlogger.atlassian.net/browse/M2-4898)
This PR adds some new attributes for covering Sign-up, Login and other screens with auto-tests
-  adds aqa attribute into error-text component
- adds aqa attribute into no-items component

M2-4898: [Mobile] Applets, Registration & Login pages - add aqa attributes

---

src/entities/alert/ui/Alert.tsx
src/entities/alert/ui/AlertList.tsx
src/entities/score/ui/Score.tsx
src/entities/score/ui/ScoreList.tsx
src/widgets/survey/ui/Summary.tsx

🔗 [Jira Ticket M2-5267](https://mindlogger.atlassian.net/browse/M2-5267)
This PR adds some new attributes for covering Summary screen with auto-tests
-  adds some new aqa attributes

M2-5267: [Mobile] Report summary screen: add aqa test-attributes

---

src/features/sign-up/ui/SignUpPasswordRequirements.tsx

Issue: [M2-5361](https://mindlogger.atlassian.net/browse/M2-5361)
[M2-5361]: https://mindlogger.atlassian.net/browse/M2-5361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-5361: Fix password requirements validation

---

.github/pull_request_template.md
src/shared/ui/SketchCanvas/SketchCanvas.tsx

Fixes:
https://mindlogger.atlassian.net/browse/M2-5292
Chore:
https://mindlogger.atlassian.net/browse/M2-5512

Sync with dev [dev -> qa]

---

src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
src/shared/lib/analytics/AnalyticsService.ts

🔗 [Jira Ticket M2-4990](https://mindlogger.atlassian.net/browse/M2-4990)
This PR adds the mix panel event when user taps on event-based notification / reminder
- Extended the enum MixEvents, added new event there, and included into the notification tap handler

M2-4990: Mixpanel Tracking: Notification,reminders, and alerts

---

package.json

Fixes:
https://mindlogger.atlassian.net/browse/M2-5813
https://mindlogger.atlassian.net/browse/M2-5814
https://mindlogger.atlassian.net/browse/M2-5809
Application logs:
https://mindlogger.atlassian.net/browse/M2-4278
Bump version to 1.2.1

Sync with qa [dev -> qa -> uat]

---

src/shared/ui/SketchCanvas/DrawingGesture.ts

🔗 [Jira Ticket M2-5811](https://mindlogger.atlassian.net/browse/M2-5811)
- Tap handling to create a dot
- Long press handling to create a dot

M2-5811: Added tap and long tap handling

---

src/features/logout/model/hooks.ts
src/features/logout/ui/LogoutRowButton.tsx
src/screens/ui/SettingsScreen.tsx

🔗 [Jira Ticket M2-6014](https://mindlogger.atlassian.net/browse/M2-6014)
- Adds Event Emmiter subscription on logout event in order to set the loading view.
- Event emmition on the actual logout operation, after all checks (e.g. against Data, Internet connection) have passed.

M2-6014: Do not show loader when checking data or Internet connection

---

package.json
src/entities/activity/lib/services/AnswersUploadService.ts
src/entities/activity/lib/types/uploadAnswers.ts
src/shared/api/services/answerService.ts
src/shared/lib/utils/dateTime.ts
src/widgets/survey/ui/Finish.tsx
src/widgets/survey/ui/Intermediate.tsx

Fixes:
https://mindlogger.atlassian.net/browse/M2-6036

Sync with dev [release/1.2.2 -> qa]

---

ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json

- A fix for ios project structure
- Version bump

Fix: ios project structure & version bump

---

src/widgets/survey/ui/Intermediate.tsx

Removed duplicated line from Intermediate screen which was caused by wrong merging

fix: removed duplicated line

---

src/shared/api/services/fileService.ts
src/shared/lib/services/Logger.ts

🔗 [Jira Ticket M2-5839](https://mindlogger.atlassian.net/browse/M2-5839)
- Fix logs optimization sending issue

M2-5839: [Mobile] Optimization for sending logs doesn't work

---

src/entities/abTrail/lib/utils/calculation.getEquidistantPoint.test.ts
src/entities/abTrail/lib/utils/calculation.ts
src/features/pass-survey/model/tests/ShiftCalculator.test.ts
src/features/pass-survey/model/tests/precompiled-pipelines.test.ts
src/shared/lib/analytics/AnalyticsService.test.ts
src/shared/lib/analytics/AnalyticsService.ts
src/shared/lib/analytics/IAnalyticsService.ts
src/shared/lib/analytics/MixpanelAnalytics.ts
src/widgets/survey/model/tests/pipelineBuilder.multiple.test.ts
src/widgets/survey/model/tests/pipelineBuilder.single.test.ts

🔗 [Jira Ticket M2-5670](https://mindlogger.atlassian.net/browse/M2-5670)
🔗 [Jira Ticket M2-5672](https://mindlogger.atlassian.net/browse/M2-5672)
🔗 [Jira Ticket M2-5674](https://mindlogger.atlassian.net/browse/M2-5674)
- Added unit tests for getEquidistantPoint
- Added unit tests for Mixpanel analytics
- Added unit tests for flow pipeline build and for ab trails pipeline build

M2-5674, M2-5672, M2-5670: [Mobile] Unit tests for getEquidistantPoint, analytics etc.

---

jest.setup.js
src/entities/event/model/AvailableToEvaluator.test.ts
src/entities/event/model/AvailableToEvaluator.ts
src/widgets/survey/model/services/CollectCompletionsService.ts
src/widgets/survey/model/services/tests/CollectCompletionsService.collectAll.test.ts
src/widgets/survey/model/services/tests/CollectCompletionsService.collectForEntity.test.ts
src/widgets/survey/model/services/tests/testHelpers.ts

Added unit tests that cover AvailableToEvaluator, CollectCompletionsService
🔗 [Jira Ticket M2-6124](https://mindlogger.atlassian.net/browse/M2-6124)
🔗 [Jira Ticket M2-6125](https://mindlogger.atlassian.net/browse/M2-6125)
🔗 [Jira Ticket M2-6126](https://mindlogger.atlassian.net/browse/M2-6126)

M2-6124, M2-6125, M2-6126: Unit tests for: AvailableToEvaluator, CollectCompletionsService

---

src/shared/lib/utils/survey/survey.test.ts

Add unit tests for survey-utils
🔗 [Jira Ticket M2-6129](https://mindlogger.atlassian.net/browse/M2-6129)

M2-6129: [Mobile] Unit tests for survey utils

---

package.json

Bump version to 1.3.1

---

assets/translations/en.json
assets/translations/fr.json

🔗 [Jira Ticket M2-6116](https://mindlogger.atlassian.net/browse/M2-6116)
- [Translation updates](https://mindlogger.atlassian.net/browse/M2-6116)

M2-6116: [Mobile App] 'Logout Warning' message is need to be updated

---

assets/translations/en.json
assets/translations/fr.json

Fixes:
https://mindlogger.atlassian.net/browse/M2-6116

Sync with release/1.3.1 [release/1.3.1 -> qa]

---

assets/translations/en.json
assets/translations/fr.json

Fixes:
https://mindlogger.atlassian.net/browse/M2-6116

Sync with release/1.3.1 [release/1.3.1 -> uat]

---

src/shared/api/services/fileService.ts

Fix S3 upload issue for arbitrary server
🔗 [Jira Ticket M2-6236](https://mindlogger.atlassian.net/browse/M2-6236)

M2-6236: Fix S3 upload issue for arbitrary server

---

assets/translations/en.json
assets/translations/fr.json

Sync `dev` with the latest changes from `release/1.3.1`

Sync dev with release/1.3.1

---

src/widgets/survey/model/mappers.ts

🔗 [Jira Ticket M2-5877](https://mindlogger.atlassian.net/browse/M2-5877)
- Fixed stacked slider answer issue

M2-5877: [Mobile app] Data Export: '0' value is missed in the 'Response' column

---

package.json

Bump version 1.3.2

---

assets/translations/en.json
assets/translations/fr.json
src/abstract/lib/types/primitive.ts
src/entities/abTrail/lib/types/test.ts
src/entities/abTrail/ui/AbCanvas.tsx
src/entities/abTrail/ui/AbTest.tsx
src/features/pass-survey/lib/alerts.ts
src/features/pass-survey/lib/index.ts
src/features/pass-survey/lib/services/SkipService.ts
src/features/pass-survey/lib/services/UserActionsPostProcessorService.ts
src/features/pass-survey/lib/services/index.ts
src/features/pass-survey/lib/types/payload.ts
src/features/pass-survey/lib/types/userAction.ts
src/features/pass-survey/model/hooks/useActivityState.ts
src/features/pass-survey/model/hooks/useActivityStepper.ts
src/features/pass-survey/model/hooks/useUserActionCreator.ts
src/features/pass-survey/model/hooks/useUserActionManager.ts
src/features/pass-survey/ui/ActivityStepper.tsx
src/shared/api/services/answerService.ts
src/shared/ui/Stepper/NextButton.tsx
src/shared/ui/Stepper/index.tsx
src/widgets/survey/model/mappers.ts

🔗 [Jira Ticket M2-5017](https://mindlogger.atlassian.net/browse/M2-5017)
- A/B Trails - Save Incomplete Round of the Test and Continue feature implementation
Added 2 new types of userActions, added maximumIndex to AbTrails response.

M2-5017: A/B Trails - Save Incomplete Round of the Test and Continue

---

src/shared/lib/analytics/AnalyticsService.ts
src/widgets/survey/model/services/ConstructCompletionsService.ts
src/widgets/survey/ui/Intermediate.tsx

🔗 [Jira Ticket M2-5550](https://mindlogger.atlassian.net/browse/M2-5550)
- Add Submit ID attribute into Assessment Completed mixpanel event
- Changed / fixed track of the event for Intermediate screen (comment added in Jira ticket)

M2-5550: [Mobile App] Mixpanel Tracking: Sumbit_id in event properties

---

src/widgets/survey/model/mappers.input.mock.ts
src/widgets/survey/model/mappers.output.mock.ts
src/widgets/survey/model/mappers.test.ts
src/widgets/survey/model/performanceTasks.input.mock.ts
src/widgets/survey/model/performanceTasks.output.mock.ts

Added unit tests for activity entity mapToActivity function all items except Flanker
🔗 [Jira Ticket M2-6303](https://mindlogger.atlassian.net/browse/M2-6303)

M2-6303: Unit tests for widgets survey mapAnswersToDto function

---

src/entities/abTrail/ui/AbCanvas.tsx
src/widgets/survey/model/performanceTasks.input.mock.ts
src/widgets/survey/model/performanceTasks.output.mock.ts

🔗 [Jira Ticket M2-6376](https://mindlogger.atlassian.net/browse/M2-6376)
- A/B Trails - Fixed incomplete state for AbTrails item

M2-6376: [Mobile app] A/B Trails: The trail is considered completed if all points except the last one were connected

---

android/app/build.gradle
ios/MindloggerMobile dev-Info.plist
ios/MindloggerMobile qa-Info.plist
ios/MindloggerMobile staging-Info.plist
ios/MindloggerMobile uat-Info.plist
ios/MindloggerMobile.xcodeproj/project.pbxproj
ios/MindloggerMobile/Info.plist
src/entities/abTrail/ui/AbCanvas.tsx

Update version to 2.0.0
Fixed a minor bug in AB Trails

Update version to 2.0.0

---

ios/MindloggerMobile dev-Info.plist
ios/MindloggerMobile qa-Info.plist
ios/MindloggerMobile staging-Info.plist
ios/MindloggerMobile uat-Info.plist
ios/MindloggerMobile/Info.plist

chore(ios): Added CURRENT_PROJECT_VERSION variable to Info.plist files

chore(ios): Added CURRENT_PROJECT_VERSION variable to Info.plist files

---

src/entities/abTrail/lib/hooks/index.ts
src/entities/abTrail/lib/hooks/useSketchCanvasTimedVisibility.ts
src/entities/abTrail/ui/AbCanvas.tsx

🔗 [Jira Ticket M2-6436](https://mindlogger.atlassian.net/browse/M2-6436)
- A/B Trails - Fixed wrong drawing line not disappearing bug

M2-6436: Fixed AbTrails wrong drawing line not disappearing bug

---

src/entities/abTrail/lib/hooks/useSketchCanvasTimedVisibility.ts
src/entities/abTrail/ui/AbCanvas.tsx

🔗 [Jira Ticket M2-6484](https://mindlogger.atlassian.net/browse/M2-6484)
- A/B Trails - Fixed sketch canvas hiding timeout

M2-6484: A/B Trails: It is not possible to draw a new line while incorrect line is shown

---

src/entities/event/model/tests/mappers.test.ts
src/features/pass-survey/model/tests/streamEventMapper.input.mock.ts
src/features/pass-survey/model/tests/streamEventMapper.test.ts

Unit tests for pass survey feature mappers (streamEventMapper) and event entity mappers
🔗 [Jira Ticket M2-6361](https://mindlogger.atlassian.net/browse/M2-6361)
🔗 [Jira Ticket M2-6362](https://mindlogger.atlassian.net/browse/M2-6362)

M2-6362: Unit tests for pass survey feature , event entity

---

src/entities/applet/model/tests/mappers.input.mock.ts
src/entities/applet/model/tests/mappers.output.mock.ts
src/entities/applet/model/tests/mappers.test.ts

Added unit tests for applet entity mappers
🔗 [Jira Ticket M2-6360](https://mindlogger.atlassian.net/browse/M2-6360)

M2-6360:  Unit tests for entities applet mappers

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
src/entities/abTrail/lib/hooks/useSketchCanvasTimedVisibility.ts
src/entities/abTrail/ui/AbCanvas.tsx

Sync dev with release/2.0.0 recent features and fixes

Sync dev with release/2.0.0

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/entities/activity/lib/types/activity.ts
src/entities/activity/model/mappers.input.mock.ts
src/entities/activity/model/mappers.output.mock.ts
src/entities/activity/model/mappers.ts
src/entities/drawer/lib/utils/constants.ts
src/entities/drawer/lib/utils/helpers.ts
src/entities/drawer/ui/DrawingTest/DrawingTest.tsx
src/entities/drawer/ui/DrawingTest/DrawingTestLegacyLayout.tsx
src/entities/drawer/ui/DrawingTest/DrawingTestNewLayout.tsx
src/entities/drawer/ui/DrawingTest/index.ts
src/entities/drawer/ui/index.ts
src/features/pass-survey/lib/types/payload.ts
src/features/pass-survey/model/hooks/mockActivities.ts
src/features/pass-survey/model/tests/testHelpers.ts
src/features/pass-survey/ui/ActivityItem.tsx
src/shared/api/services/ActivityItemDto.ts
src/shared/api/services/mockActivities.ts
src/shared/lib/types/index.ts
src/shared/lib/types/space.ts
src/widgets/survey/model/performanceTasks.input.mock.ts

🔗 [Jira Ticket M2-6576](https://mindlogger.atlassian.net/browse/M2-6576)
- Legacy layout support
- Backend integration
- Version update

M2-6576: legacy layout support

---

src/shared/lib/constants/dateTime.ts
src/shared/ui/DateTimePicker.tsx
src/shared/ui/survey/DatePickerItem.tsx
src/shared/ui/survey/TimePickerItem.tsx
src/shared/ui/survey/TimeRangeItem.tsx
src/shared/ui/survey/tests/TimePickerItem.test.tsx

🔗 [Jira Ticket M2-6446](https://mindlogger.atlassian.net/browse/M2-6446)
- Removed default value for Time item
- Added placeholder prop to DateTimePicker component

M2-6446: Remove auto-default for the Time item

---

src/features/pass-survey/lib/types/payload.ts
src/features/pass-survey/model/AnswerValidator.ts
src/features/pass-survey/model/hooks/useActivityStepper.ts
src/features/pass-survey/model/tests/AnswerValidator.test.ts
src/features/pass-survey/model/tests/testHelpers.ts
src/shared/api/services/answerService.ts
src/shared/ui/survey/TimeRangeItem.tsx
src/shared/ui/survey/tests/TimeRangeItem.test.tsx
src/widgets/survey/model/mappers.ts

🔗 [Jira Ticket M2-6326](https://mindlogger.atlassian.net/browse/M2-6326)
- removing default date value for TimeRange item
- a fix for unit tests
- Changed time Range item contract

M2-6326: Removed auto-default value for TimeRange item

---

src/widgets/survey/lib/storageHelpers.ts
src/widgets/survey/ui/Intermediate.tsx

🔗 [Jira Ticket M2-6465](https://mindlogger.atlassian.net/browse/M2-6465)
- Disabled the Back button on the Intermediate screen if an activity record has been deleted due to its submission

M2-6465: Disabled the Back button if activity record has been removed

---

assets/translations/en.json
assets/translations/fr.json
src/features/pass-survey/lib/contexts/ActivityIdentityContext.ts
src/features/pass-survey/ui/ActivityStepper.tsx
src/features/pass-survey/ui/Header.tsx
src/features/pass-survey/ui/HeaderProgress.tsx
src/shared/lib/constants/colors.ts
src/shared/ui/HeaderProgressBar.tsx
src/shared/ui/TimeRemaining.tsx
src/shared/ui/index.tsx
src/widgets/survey/ui/FlowElementSwitch.tsx
src/widgets/survey/ui/FlowSurvey.tsx

📝 Description
🔗 [Jira Ticket M2-6500](https://mindlogger.atlassian.net/browse/M2-6500)
🔗 [Jira Ticket M2-6919](https://mindlogger.atlassian.net/browse/M2-6919)
🔗 [Jira Ticket M2-6918](https://mindlogger.atlassian.net/browse/M2-6918)
Updated Activity header UI
Added translations

M2-6500: Updated Activity Header UI

---

src/shared/ui/survey/CheckBox/CheckBox.item.tsx
src/shared/ui/survey/RadioActivityItem/RadioActivityItem.tsx

🔗 [Jira Ticket M2-6652](https://mindlogger.atlassian.net/browse/M2-6652)
- Fix some attributes to allow aqa continue some tests

M2-6652: [Mobile] Single select options and tooltips

---

src/features/pass-survey/ui/ActivityStepper.tsx
src/features/pass-survey/ui/Header.tsx
src/screens/ui/ActivityListScreen.tsx
src/shared/ui/Button.tsx
src/shared/ui/Stepper/ActionButton.tsx
src/shared/ui/Stepper/BackButton.tsx
src/shared/ui/Stepper/NextButton.tsx
src/shared/ui/Stepper/UndoButton.tsx

📝 Description
🔗 [Jira Ticket M2-6503](https://mindlogger.atlassian.net/browse/M2-6503)
Updated Activity navigation buttons UI

M2-6503: Updated Activity navigation buttons UI

---

assets/translations/en.json
assets/translations/fr.json
src/features/pass-survey/ui/ActivityItem.tsx
src/features/pass-survey/ui/ActivityStepper.tsx
src/features/pass-survey/ui/Header.tsx
src/features/pass-survey/ui/ProgressWithTimer.tsx
src/features/pass-survey/ui/Timer.tsx
src/shared/ui/ProgressBar.tsx

📝 Description
🔗 [Jira Ticket M2-6502](https://mindlogger.atlassian.net/browse/M2-6502)
Updated Activity item timer UI

M2-6502: Updated Activity item timer UI

---

android/app/build.gradle
android/app/src/production/google-services.json

🔗 [Jira Ticket M2-6930](https://mindlogger.atlassian.net/browse/M2-6930)
1. Added `applicationIdSuffix` for Production Flavor to be able to upload new production builds to new app on Google Play Console.
2. Added a new `google-services.json `for Production Flavor to enable Crashlytics and Firebase Messaging

M2-6930: Added new application Id for Production app

---

src/features/pass-survey/ui/ActivityStepper.tsx

🔗 [Jira Ticket M2-6982](https://mindlogger.atlassian.net/browse/M2-6982)
🔗 [Jira Ticket M2-6983](https://mindlogger.atlassian.net/browse/M2-6983)
🔗 [Jira Ticket M2-6984](https://mindlogger.atlassian.net/browse/M2-6984)
- Fixed activity bottom navigation and activity timer appearance issues

M2-6982: Fixed activity bottom navigation and activity timer appearance issues

---

src/screens/ui/AppletsScreen.tsx

🔗 [Jira Ticket M2-7381](https://mindlogger.atlassian.net/browse/M2-#)
The "LORIS" work was removed from the bottom link on the Applet List screen.

M2-7381: removed loris word from bottom link

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/screens/ui/AppletsScreen.tsx

Release/2.1.0 [dev]

---

package.json
src/entities/activity/lib/services/tests/AnswersUploadService.test.js
src/shared/lib/utils/survey/survey.test.ts
src/widgets/survey/model/services/tests/CollectCompletionsService.collectAll.test.ts
src/widgets/survey/model/services/tests/CollectCompletionsService.collectForEntity.test.ts

🔗 [Jira Ticket M2-7452](https://mindlogger.atlassian.net/browse/M2-7452)
- [Mobile] Fix unit tests for modules: AnswersUploadService, CollectCompletionsService, survey
- Uncover unit tests

M2-7452: [Mobile] Fix unit tests for modules: AnswersUploadService, CollectCompletionsService, etc.

---

src/shared/ui/survey/tests/DatePickerItem.test.tsx

- [V] Tests for the changes have been added
- [V] Related documentation has been added / updated
🔗 [Jira Ticket M2-7413](https://mindlogger.atlassian.net/browse/M2-7413)
- Tests
-  /Users/felipeimp/mindLogger/mindlogger-app-refactor/src/shared/ui/survey/tests/DatePickerItem.test.tsx
`yarn test`
One test was fixed

fix: update DatepickerItem test

---

src/entities/activity/lib/services/AnswersUploadService.ts
src/entities/activity/lib/types/uploadAnswers.ts
src/shared/api/services/answerService.ts

🔗 [Jira Ticket M2-7222](https://mindlogger.atlassian.net/browse/M2-7222)

M2-7222: Autocompleted activity responses are uploaded from the queue(pink banner) only for one device

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/entities/activity/lib/services/AnswersUploadService.ts
src/entities/activity/lib/types/uploadAnswers.ts
src/shared/api/services/answerService.ts
src/shared/lib/featureFlags/FeatureFlags.types.ts

Release/2.1.1 [dev]

---

assets/translations/en.json
assets/translations/fr.json
src/features/tap-on-notification/lib/alerts.ts
src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
src/features/tap-on-notification/model/services/NotificationPostponer.ts
src/screens/model/checkEntityAvailability.ts
src/screens/ui/RootNavigator.tsx
src/shared/lib/services/ActionPostponer.ts
src/shared/lib/services/index.ts
src/widgets/survey/model/services/InterimInActionPostponer.ts
src/widgets/survey/ui/UploadRetryBanner.tsx
src/widgets/survey/ui/completion/AutoCompletion.tsx

🔗 [Jira Ticket M2-7321](https://mindlogger.atlassian.net/browse/M2-7321)
🔗 [Jira Ticket M2-7433](https://mindlogger.atlassian.net/browse/M2-7433)
- Delayed notification
- Pink banner minor changes

M2-7321, M2-7433: [Mobile]: Handle tap on notification while autocompletion is working

---

src/shared/lib/hooks/useUploadProgress.ts
src/shared/lib/observables/uploadProgressObservable.ts

Reworking gitflow on the mobile repo to follow other repos, this task was previously merged to a separate release branch
feat: removing wait from use upload progress M2-7771 (#858)

merge release 2.2.3 to dev

---

src/entities/activity/model/mappers.ts

🔗 [Jira Ticket M2-7807](https://mindlogger.atlassian.net/browse/M2-7807)
this PR add conditional logic support to message type.
Result:
https://github.com/user-attachments/assets/25d16939-4629-4b2b-94ef-d9a3cdf9e011
1 - launch the app and admin.
2 - In Admin, create an applet or open an existing one.
3 - go to: Activities > activity name > items  and create an item type to be the conditional logic such as slider and create a message item.
4- go to: Activities > activity name > Item Flow and create a conditional logic exampe:
5 - open the app and choose the flow that contain the conditional logic you created.
This PR is a small part of this ticket:
https://mindlogger.atlassian.net/browse/M2-7011

M2-7807: adding conditional logic support to message

---

README.md
fastlane/Fastfile
fastlane/README.md

Automatically adds `chore: bump version X.X.X (xxxx)` commit when doing yarn bump
- Run `yarn bump`
- Check last commit message

chore: auto version bump commit

---

assets/translations/el.json
assets/translations/en.json
assets/translations/fr.json
src/entities/localization/lib/setupLocalization.ts
src/shared/lib/types/language.ts
src/shared/lib/utils/dateTime.ts

Adds Greek language localization support.
🔗 [Jira Ticket M2-7800](https://mindlogger.atlassian.net/browse/M2-7800)
| 1 | 2 | 3 |
| -------------------------------------- | ------------------------------------- | - |
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 52 08](https://github.com/user-attachments/assets/4b8ac0e8-ba76-4e09-888d-63bf55010ea1) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 32 13](https://github.com/user-attachments/assets/6340f393-85ca-4180-81e8-c7288b19c14f) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 34 49](https://github.com/user-attachments/assets/28ed4d95-08b9-46e3-a089-5d9a61dafd82) | 
| 1 | 2 | 3 | …

feat: add Greek language option (M2-7800)

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
src/entities/activity/lib/hooks/useQueueProcessing.ts
src/widgets/survey/model/hooks/useAutoCompletion.ts

Reverting #884 as it only partially solved the issue (didn't fix it for offline), and may have introduced more regressions (to be confirmed by QA).
N/A

fix: Revert "chore: add applets refresh after answers submission (#884)" (M2-8144)

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/entities/activity/lib/hooks/useQueueProcessing.ts
src/widgets/survey/model/hooks/useAutoCompletion.ts

Release/2.6.0 [dev]

---

android/app/build.gradle
ios/FlankerNativeComponents/GameManager.swift
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json

Sync Release/2.6.1 back to dev

Sync Release/2.6.1 [dev]

---

src/screens/ui/RootNavigator.tsx

🔗 [Jira Ticket M2-8137](https://mindlogger.atlassian.net/browse/M2-8137)
Turning Back button into translatable button.
- Launch the App.
- change the language to a desired language.
- go to some page that has "Back Button" such as create account.

setting Back button translatable

---

src/entities/activity/model/mappers.ts
src/entities/conditional-logic/model/conditions.ts

🔗 [Jira Ticket M2-8346](https://mindlogger.atlassian.net/browse/M2-8346)
Maping payload properly, and fixing the between and outside of time range condition 
https://github.com/user-attachments/assets/3e0ecc8a-37e1-440c-9828-d1dbb55ea134
1 - create an activity with between or outside of time range logic.
2 - launch the app
3 - check if the condition responds to the expected

fix: mapping payload and fixing between and outside of time range (M2-8346)

---

src/features/pass-survey/model/pipelineBuilder.ts

🔗 [Jira Ticket M2-8319](https://mindlogger.atlassian.net/browse/M2-8319)
Fixing slider row conditional logic putting conditional logic in StackedSlider in pipelineBuilder
https://github.com/user-attachments/assets/3c52c3c0-747f-4e6d-a6a1-6c3cb00f8f82
1 - create an applet with slider row and tie the slider row to some conditional logic, (similar to the screen shot I left)
2 - launch the app
3 - check if the flow is responding properly.

M2-8319: fixing slider row conditional logic

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/entities/activity/model/mappers.ts
src/entities/conditional-logic/model/conditions.ts
src/features/pass-survey/model/pipelineBuilder.ts

Release/2.7.0 [dev]

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json

Release/2025.01.1 [dev]

---

src/entities/activity/lib/types/conditionalLogic.ts
src/features/pass-survey/model/PipelineVisibilityChecker.ts
src/shared/api/services/ActivityItemDto.ts

Updates `payload.time` parsing for Time and TimeRange item types to match expected format from Admin.
🔗 [Jira Ticket M2-8615](https://mindlogger.atlassian.net/browse/M2-8615)
🔗 [Jira Ticket M2-8616](https://mindlogger.atlassian.net/browse/M2-8616)
🔗 [Jira Ticket M2-8617](https://mindlogger.atlassian.net/browse/M2-8617)
https://github.com/user-attachments/assets/32d8d6b6-2dca-4f7b-a100-20952c310f64
Use the provided applet available in the `dev` environment:
```
Credentials:
user: pr573@example.com
pass: pr573!
```
- Complete the provided Activities for testing Time, Time Range and Date item type conditional logic
- Each activity includes a summary of test cases and expected validations
Alternatively you can create a new applet in your local environment:
- Create an applet containing Time, …

fix: update Time and TimeRange conditional logic (M2-8615, M2-8616, 8617)

---

.github/dependabot.yml

🔗 [Jira Ticket M2-8023](https://mindlogger.atlassian.net/browse/M2-8023)
- Added dependabot checks

chore: Adding dependabot

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj

Release/2025.03.2 [dev]

---

README.md
android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
src/features/pass-survey/model/hooks/useActivityStepper.ts

Release/2025.03.2 [main]

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json

Merging `release/2025.05.3` to dev

Release/2025.05.3 [dev]

---

android/app/build.gradle
ios/MindloggerMobile.xcodeproj/project.pbxproj
package.json
src/app/ui/AppProvider/NavigationProvider.tsx
src/features/pass-survey/ui/ActivityStepper.tsx
src/screens/ui/AutocompletionScreen.tsx
src/screens/ui/InProgressActivityScreen.tsx
src/shared/lib/constants/colors.ts
src/widgets/survey/ui/Finish.tsx
src/widgets/survey/ui/Summary.tsx
src/widgets/survey/ui/completion/containers.tsx

Merging `release/2025.06.2` to `main`

Release/2025.06.2 [main]

---

README.md

Added line about Browserstack to the readme.

docs: Add browserstack to readme (M2-5535)
